import type { ERAcuteEvent, PatientAdvocateEvent } from './operationalTypes';

export const mockERAcuteEvents: ERAcuteEvent[] = [
  {
    id: 'er-1', patient_id: 'PT-4401', acuity_level: 2, chief_complaint: 'Chest pain, diaphoresis',
    arrival_method: 'ambulance', triage_wait_minutes: 0, bed_assignment_minutes: 3, provider_seen_minutes: 5,
    disposition: 'admitted', boarding_hours: 6.5, left_without_seen: false, overcrowding_at_arrival: true,
    shift: 'PM', day_of_week: 'Monday', department_zone: 'Zone A — Critical',
    notes: 'STEMI alert activated. Cath lab occupied — 45min delay to intervention. Boarding in hallway post-cath.',
    created_at: '2026-04-14T19:30:00Z',
  },
  {
    id: 'er-2', patient_id: 'PT-4402', acuity_level: 3, chief_complaint: 'Abdominal pain, vomiting x2 days',
    arrival_method: 'walk-in', triage_wait_minutes: 28, bed_assignment_minutes: 55, provider_seen_minutes: 82,
    disposition: 'admitted', boarding_hours: 4.2, left_without_seen: false, overcrowding_at_arrival: true,
    shift: 'PM', day_of_week: 'Monday', department_zone: 'Zone B — Acute',
    notes: 'CT showed appendicitis. Surgical consult delayed 90min due to OR volume.',
    created_at: '2026-04-14T20:15:00Z',
  },
  {
    id: 'er-3', patient_id: 'PT-4403', acuity_level: 4, chief_complaint: 'Laceration, left forearm',
    arrival_method: 'walk-in', triage_wait_minutes: 42, bed_assignment_minutes: 68, provider_seen_minutes: 95,
    disposition: 'discharged', boarding_hours: 0, left_without_seen: false, overcrowding_at_arrival: true,
    shift: 'PM', day_of_week: 'Monday', department_zone: 'Zone C — Fast Track',
    notes: 'Simple repair. Total ED LOS 3.5 hours for a 15-minute procedure.',
    created_at: '2026-04-14T21:00:00Z',
  },
  {
    id: 'er-4', patient_id: 'PT-4404', acuity_level: 3, chief_complaint: 'Fall, hip pain, elderly',
    arrival_method: 'ambulance', triage_wait_minutes: 8, bed_assignment_minutes: 22, provider_seen_minutes: 35,
    disposition: 'admitted', boarding_hours: 8.0, left_without_seen: false, overcrowding_at_arrival: false,
    shift: 'Night', day_of_week: 'Tuesday', department_zone: 'Zone B — Acute',
    notes: 'Hip fracture confirmed. Ortho notified but no OR availability until morning. Patient boarded overnight.',
    created_at: '2026-04-13T02:30:00Z',
  },
  {
    id: 'er-5', patient_id: 'PT-4405', acuity_level: 5, chief_complaint: 'Prescription refill request',
    arrival_method: 'walk-in', triage_wait_minutes: 65, bed_assignment_minutes: 0, provider_seen_minutes: 0,
    disposition: 'discharged', boarding_hours: 0, left_without_seen: true, overcrowding_at_arrival: true,
    shift: 'PM', day_of_week: 'Monday', department_zone: 'Zone C — Fast Track',
    notes: 'Patient left after 65-minute wait. Non-emergent — could have been redirected to urgent care.',
    created_at: '2026-04-14T18:45:00Z',
  },
  {
    id: 'er-6', patient_id: 'PT-4406', acuity_level: 1, chief_complaint: 'Unresponsive, found down',
    arrival_method: 'ambulance', triage_wait_minutes: 0, bed_assignment_minutes: 0, provider_seen_minutes: 1,
    disposition: 'admitted', boarding_hours: 2.0, left_without_seen: false, overcrowding_at_arrival: false,
    shift: 'AM', day_of_week: 'Wednesday', department_zone: 'Zone A — Critical',
    notes: 'Rapid response. Intubated in field. ICU bed secured in 2 hours.',
    created_at: '2026-04-12T07:10:00Z',
  },
  {
    id: 'er-7', patient_id: 'PT-4407', acuity_level: 3, chief_complaint: 'Shortness of breath, history of CHF',
    arrival_method: 'walk-in', triage_wait_minutes: 15, bed_assignment_minutes: 40, provider_seen_minutes: 55,
    disposition: 'observation', boarding_hours: 3.5, left_without_seen: false, overcrowding_at_arrival: false,
    shift: 'AM', day_of_week: 'Thursday', department_zone: 'Zone B — Acute',
    notes: 'Placed on obs status. Diuresis effective. Discharged next day.',
    created_at: '2026-04-11T09:20:00Z',
  },
  {
    id: 'er-8', patient_id: 'PT-4408', acuity_level: 4, chief_complaint: 'Ankle sprain, ambulatory',
    arrival_method: 'walk-in', triage_wait_minutes: 50, bed_assignment_minutes: 75, provider_seen_minutes: 90,
    disposition: 'discharged', boarding_hours: 0, left_without_seen: false, overcrowding_at_arrival: true,
    shift: 'PM', day_of_week: 'Friday', department_zone: 'Zone C — Fast Track',
    notes: 'X-ray negative. Splinted. Long wait due to Friday PM surge.',
    created_at: '2026-04-10T17:30:00Z',
  },
];

export const mockPatientAdvocateEvents: PatientAdvocateEvent[] = [
  {
    id: 'pa-1', patient_id: 'PT-3301', event_category: 'missed_assessment',
    severity: 'high', description: 'Neuro checks not performed q2h post-craniotomy',
    expected_standard: 'Neuro assessment every 2 hours for first 24h post-craniotomy',
    actual_finding: 'Last documented neuro check was 6 hours prior', deviation_minutes: 240,
    unit: '4 North — Neuro', shift: 'Night', day_of_week: 'Sunday', responsible_role: 'RN',
    was_reported: false, resolution_status: 'open',
    notes: 'Patient was stable but protocol was not followed. No adverse outcome.',
    created_at: '2026-04-13T04:00:00Z',
  },
  {
    id: 'pa-2', patient_id: 'PT-3302', event_category: 'medication_delay',
    severity: 'high', description: 'Antibiotic delayed 3 hours post-surgical',
    expected_standard: 'First dose antibiotics within 1 hour of OR end time',
    actual_finding: 'Antibiotic administered 4 hours after OR completion', deviation_minutes: 180,
    unit: '3 South — Surgical', shift: 'PM', day_of_week: 'Monday', responsible_role: 'RN',
    was_reported: true, resolution_status: 'investigating',
    resolution_notes: 'Pharmacy delay compounded by shift handoff gap.',
    notes: 'Patient developed fever 12h later. Unclear if related.',
    created_at: '2026-04-14T16:30:00Z',
  },
  {
    id: 'pa-3', patient_id: 'PT-3303', event_category: 'fall_risk_miss',
    severity: 'critical', description: 'Fall risk assessment not updated after opioid administration',
    expected_standard: 'Reassess fall risk after any new sedating medication',
    actual_finding: 'Patient found on floor 2 hours after IV morphine. Fall risk score not updated.',
    deviation_minutes: 120, unit: '5 East — Med/Surg', shift: 'Night', day_of_week: 'Tuesday',
    responsible_role: 'RN', was_reported: true, resolution_status: 'escalated',
    resolution_notes: 'Incident report filed. Patient sustained minor contusion.',
    notes: 'Bed alarm was not activated despite high fall risk medications.',
    created_at: '2026-04-12T03:15:00Z',
  },
  {
    id: 'pa-4', patient_id: 'PT-3304', event_category: 'handoff_failure',
    severity: 'high', description: 'Critical lab result not communicated during shift change',
    expected_standard: 'All critical values communicated in real-time and during handoff',
    actual_finding: 'Potassium 6.2 resulted at 1845, not addressed until 2130 when night RN reviewed chart',
    deviation_minutes: 165, unit: '3 South — Surgical', shift: 'PM', day_of_week: 'Wednesday',
    responsible_role: 'RN', was_reported: true, resolution_status: 'resolved',
    resolution_notes: 'SBAR handoff tool revised. Critical value acknowledgment now requires timestamp.',
    notes: 'Patient received emergent treatment. No lasting harm.',
    created_at: '2026-04-11T21:30:00Z',
  },
  {
    id: 'pa-5', patient_id: 'PT-3305', event_category: 'documentation_gap',
    severity: 'medium', description: 'Skin assessment missing for 3 consecutive shifts',
    expected_standard: 'Skin integrity assessment every shift for immobile patients',
    actual_finding: 'No skin assessment documented for 36 hours. Stage 1 pressure injury found on sacrum.',
    deviation_minutes: 2160, unit: '4 North — Neuro', shift: 'AM', day_of_week: 'Thursday',
    responsible_role: 'RN', was_reported: false, resolution_status: 'open',
    notes: 'Patient is high-risk for pressure injury. Wound care consulted.',
    created_at: '2026-04-10T08:00:00Z',
  },
  {
    id: 'pa-6', patient_id: 'PT-3306', event_category: 'timing_deviation',
    severity: 'medium', description: 'Vitals not taken for 8 hours on med/surg patient',
    expected_standard: 'Vitals every 4 hours minimum for med/surg patients',
    actual_finding: 'Gap from 2300 to 0700. Patient was asymptomatic.',
    deviation_minutes: 240, unit: '5 East — Med/Surg', shift: 'Night', day_of_week: 'Monday',
    responsible_role: 'RN', was_reported: false, resolution_status: 'open',
    notes: 'Staffing was 1:7 ratio. RN had two admissions during the gap.',
    created_at: '2026-04-14T07:00:00Z',
  },
  {
    id: 'pa-7', patient_id: 'PT-3307', event_category: 'missed_assessment',
    severity: 'high', description: 'Pain reassessment not performed within 1 hour of PRN opioid',
    expected_standard: 'Reassess pain within 60 minutes of IV opioid administration',
    actual_finding: 'No pain reassessment documented for 4 hours after IV dilaudid.',
    deviation_minutes: 180, unit: '3 South — Surgical', shift: 'PM', day_of_week: 'Friday',
    responsible_role: 'RN', was_reported: false, resolution_status: 'open',
    notes: 'Patient reported uncontrolled pain at next vital check.',
    created_at: '2026-04-09T15:00:00Z',
  },
  {
    id: 'pa-8', patient_id: 'PT-3308', event_category: 'handoff_failure',
    severity: 'medium', description: 'Pending CT results not included in nursing handoff',
    expected_standard: 'All pending diagnostic results communicated during shift handoff',
    actual_finding: 'CT abdomen results available at 1900, not reviewed until 0600 next morning.',
    deviation_minutes: 660, unit: '5 East — Med/Surg', shift: 'Night', day_of_week: 'Saturday',
    responsible_role: 'RN', was_reported: false, resolution_status: 'open',
    notes: 'CT showed no acute findings. No patient harm, but represents systemic handoff gap.',
    created_at: '2026-04-08T06:00:00Z',
  },
];
