import {
  createPDFContext, addDocumentHeader, addSectionHeader, addTitle, addBody,
  addBullet, addKeyValue, addScoreCards, addAlertBox, addDivider, addSpacer,
  addTable, addFooter, severityColor,
} from './pdfHelpers';
import type { OBAuditResult } from './obFetalTypes';

export function exportOBAuditPDF(result: OBAuditResult, filename = 'ob-fetal-audit.pdf') {
  const ctx = createPDFContext('portrait');

  addDocumentHeader(
    ctx,
    'OB Fetal Monitoring Audit',
    `Generated ${new Date(result.generatedAt).toLocaleString()} · ${result.monitoredMinutes} min monitored · ${result.windowMinutes}-min windows`,
  );

  addScoreCards(ctx, [
    { label: 'Category I windows',  value: String(result.summary.catI),  color: 'green' },
    { label: 'Category II windows', value: String(result.summary.catII), color: 'amber' },
    { label: 'Category III windows',value: String(result.summary.catIII),color: 'red' },
    { label: 'Tachysystole',        value: String(result.summary.tachysystoleWindows), color: 'amber' },
    { label: 'Critical violations', value: String(result.summary.criticalViolations), color: 'red' },
  ]);

  addSectionHeader(ctx, 'Stop-Rule Violations');
  if (!result.violations.length) {
    addAlertBox(ctx, 'No stop-rule violations detected across the monitored window.', 'success', 'Clean');
  } else {
    for (const v of result.violations) {
      addTitle(ctx, `[${v.severity.toUpperCase()}] ${v.medicationLabel} — ${new Date(v.t).toLocaleString()}`, 11);
      addKeyValue(ctx, 'Rule', v.rule);
      addKeyValue(ctx, 'Strip finding', v.stripFinding);
      addKeyValue(ctx, 'Medication action', v.medAction);
      addKeyValue(ctx, 'Charted response', v.chartedResponse);
      addKeyValue(ctx, 'Time to first stop/decrease',
        v.minutesToAction === null ? 'never documented' : `${v.minutesToAction} min`);
      addSpacer(ctx, 6);
      addDivider(ctx);
    }
    void severityColor;
  }

  addSectionHeader(ctx, 'Contraindication Ledger');
  if (!result.contraindicationChecks.length) {
    addBody(ctx, 'No Pitocin or Misoprostol doses found in the MAR.');
  } else {
    for (const c of result.contraindicationChecks) {
      addTitle(ctx, `${c.medicationLabel} — ${c.dose} @ ${new Date(c.doseEventTime).toLocaleString()}`, 11);
      if (c.clear) {
        addAlertBox(ctx, 'None documented at time of administration.', 'success');
      } else {
        for (const ci of c.contraindicationsPresent) {
          addBullet(ctx, `${ci.label} — ${ci.evidence}`);
        }
      }
      addSpacer(ctx, 4);
    }
  }

  addSectionHeader(ctx, 'Strip Timeline');
  addTable(
    ctx,
    [
      { header: 'Window', width: 110 },
      { header: 'FHR',    width: 50, align: 'right' },
      { header: 'Var.',   width: 60 },
      { header: 'Cx',     width: 36, align: 'right' },
      { header: 'Cat.',   width: 50, align: 'center' },
      { header: 'Reason', width: 210 },
    ],
    result.windows.map((w) => [
      `${new Date(w.start).toLocaleTimeString()} (${w.source})`,
      w.baselineFHR === null ? '—' : String(w.baselineFHR),
      w.variability,
      String(w.contractionCount) + (w.tachysystole ? ' ⚠' : ''),
      w.category,
      w.categoryReason,
    ]),
  );

  addFooter(ctx, 'Generated by SOUPY Audit — OB Fetal Monitoring module. Retrospective decision-support; not a replacement for clinical judgment.');

  ctx.doc.save(filename);
}
