import {
  createPDFContext, addDocumentHeader, addSectionHeader, addTitle, addSubtitle,
  addBody, addBullet, addKeyValue,
} from './pdfHelpers';

export type SelfHelpResults = {
  summary?: string;
  findings?: Array<{
    title: string;
    severity?: string;
    plainLanguage?: string;
    standardCited?: string;
    evidenceQuote?: string;
    sourceFile?: string;
    sourcePages?: number[];
  }>;
  timeline?: Array<{
    timestamp?: string;
    event: string;
    sourceFile?: string;
    sourcePages?: number[];
  }>;
  complaintPacket?: {
    intro?: string;
    sections?: Array<{ heading: string; body: string }>;
    requestedActions?: string[];
  };
  attorneySummary?: {
    caseTheory?: string;
    keyDeviations?: Array<{ title: string; whyItMatters: string; recordCitation?: string }>;
    damagesNarrative?: string;
    recordsCited?: string[];
  };
  generatedAt?: string;
};

function header(caseTitle: string | null | undefined, title: string, subtitle: string) {
  const ctx = createPDFContext('portrait');
  addDocumentHeader(ctx, title, subtitle);
  if (caseTitle) {
    addSectionHeader(ctx, 'Case');
    addKeyValue(ctx, 'Case title', caseTitle);
  }
  return ctx;
}

function disclaimer(ctx: ReturnType<typeof createPDFContext>) {
  addSectionHeader(ctx, 'Important Notice');
  addBody(
    ctx,
    'This report is generated by an automated review of records the patient or family provided. ' +
    'It is not medical advice and is not legal advice. It is intended to help a non-clinician ' +
    'understand items in their own record that appear inconsistent with widely accepted standards of care, ' +
    'and to assist in preparing a complaint or attorney consultation. Quoted text is taken verbatim from the records uploaded.'
  );
}

export function exportSelfHelpFindingsPDF(
  caseTitle: string | null | undefined,
  results: SelfHelpResults,
  filename = 'self-help-findings.pdf',
) {
  const generated = results.generatedAt ? new Date(results.generatedAt).toLocaleString() : new Date().toLocaleString();
  const ctx = header(caseTitle, 'Patient Record Review — Findings', `Prepared ${generated}`);
  if (results.summary) {
    addSectionHeader(ctx, 'Plain-Language Summary');
    addBody(ctx, results.summary);
  }

  addSectionHeader(ctx, 'Findings');
  const findings = results.findings ?? [];
  if (findings.length === 0) {
    addBody(ctx, 'No deviations from standard of care were identified in the materials provided.');
  }
  for (const f of findings) {
    addTitle(ctx, `${(f.severity ?? 'finding').toUpperCase()} — ${f.title}`, 12);
    if (f.plainLanguage) addBody(ctx, f.plainLanguage);
    if (f.standardCited) addKeyValue(ctx, 'Standard cited', f.standardCited);
    if (f.sourceFile) {
      const pages = f.sourcePages?.length ? ` (pages ${f.sourcePages.join(', ')})` : '';
      addKeyValue(ctx, 'Source', `${f.sourceFile}${pages}`);
    }
    if (f.evidenceQuote) {
      addSubtitle(ctx, 'Verbatim from record');
      addBody(ctx, `"${f.evidenceQuote}"`);
    }
  }

  disclaimer(ctx);
  ctx.doc.save(filename);
}

export function exportSelfHelpTimelinePDF(
  caseTitle: string | null | undefined,
  results: SelfHelpResults,
  filename = 'self-help-timeline.pdf',
) {
  const generated = results.generatedAt ? new Date(results.generatedAt).toLocaleString() : new Date().toLocaleString();
  const ctx = header(caseTitle, 'Patient Record Review — Timeline', `Prepared ${generated}`);
  addSectionHeader(ctx, 'Reconstructed Timeline');
  const events = results.timeline ?? [];
  if (events.length === 0) addBody(ctx, 'No timestamped events were extracted.');
  for (const e of events) {
    const t = e.timestamp || '—';
    const src = e.sourceFile ? ` · ${e.sourceFile}${e.sourcePages?.length ? ` p.${e.sourcePages.join(',')}` : ''}` : '';
    addBullet(ctx, `${t}: ${e.event}${src}`);
  }
  disclaimer(ctx);
  ctx.doc.save(filename);
}

export function exportSelfHelpComplaintPDF(
  caseTitle: string | null | undefined,
  contactName: string | null | undefined,
  contactEmail: string | null | undefined,
  results: SelfHelpResults,
  filename = 'self-help-complaint-packet.pdf',
) {
  const generated = results.generatedAt ? new Date(results.generatedAt).toLocaleString() : new Date().toLocaleString();
  const ctx = header(caseTitle, 'Patient Complaint / Grievance Packet', `Prepared ${generated}`);
  addSectionHeader(ctx, 'Submitted by');
  if (contactName) addKeyValue(ctx, 'Name', contactName);
  if (contactEmail) addKeyValue(ctx, 'Email', contactEmail);

  const packet = results.complaintPacket ?? {};
  if (packet.intro) {
    addSectionHeader(ctx, 'Statement of Concern');
    addBody(ctx, packet.intro);
  }
  for (const s of packet.sections ?? []) {
    addSectionHeader(ctx, s.heading);
    addBody(ctx, s.body);
  }
  if (packet.requestedActions?.length) {
    addSectionHeader(ctx, 'Requested Actions');
    for (const a of packet.requestedActions) addBullet(ctx, a);
  }
  disclaimer(ctx);
  ctx.doc.save(filename);
}

export function exportSelfHelpAttorneyPDF(
  caseTitle: string | null | undefined,
  results: SelfHelpResults,
  filename = 'self-help-attorney-summary.pdf',
) {
  const generated = results.generatedAt ? new Date(results.generatedAt).toLocaleString() : new Date().toLocaleString();
  const ctx = header(caseTitle, 'Attorney-Ready Case Summary', `Prepared ${generated}`);
  const a = results.attorneySummary ?? {};
  if (a.caseTheory) { addSectionHeader(ctx, 'Case Theory'); addBody(ctx, a.caseTheory); }
  if (a.keyDeviations?.length) {
    addSectionHeader(ctx, 'Key Deviations from Standard of Care');
    for (const d of a.keyDeviations) {
      addTitle(ctx, d.title, 12);
      if (d.whyItMatters) addBody(ctx, d.whyItMatters);
      if (d.recordCitation) addKeyValue(ctx, 'Record citation', d.recordCitation);
    }
  }
  if (a.damagesNarrative) { addSectionHeader(ctx, 'Damages Narrative (Patient-Reported)'); addBody(ctx, a.damagesNarrative); }
  if (a.recordsCited?.length) {
    addSectionHeader(ctx, 'Records Cited');
    for (const r of a.recordsCited) addBullet(ctx, r);
  }
  disclaimer(ctx);
  ctx.doc.save(filename);
}