import {
  createPDFContext, addDocumentHeader, addSectionHeader, addTitle, addBody,
  addBullet, addKeyValue, addAlertBox, addDivider, addSpacer, addFooter,
} from './pdfHelpers';
import type { OBAuditResult, StopRuleViolation } from './obFetalTypes';

/** A formal complaint / patient-safety packet built from the same audit result.
 *  Reads neutrally and cites the rule for each finding so it can be sent to
 *  hospital risk management, the state board of nursing, Joint Commission, or
 *  an attorney without further rewriting. */
export function exportOBComplaintPacketPDF(result: OBAuditResult, filename = 'ob-complaint-packet.pdf') {
  const ctx = createPDFContext('portrait');
  const h = result.caseHeader || {};

  addDocumentHeader(
    ctx,
    'Patient Safety Concern — L&D Care Review',
    `Prepared ${new Date(result.generatedAt).toLocaleString()} · ${result.monitoredMinutes} min monitored · ${result.windowMinutes}-min audit windows`,
  );

  addSectionHeader(ctx, 'Case Identification');
  addKeyValue(ctx, 'Patient (initials)', h.patientInitials || '—');
  addKeyValue(ctx, 'Facility', h.facility || '—');
  addKeyValue(ctx, 'Unit / Room', [h.unit, h.roomNumber].filter(Boolean).join(' · ') || '—');
  addKeyValue(ctx, 'Attending OB', h.attendingOB || '—');
  addKeyValue(ctx, 'Date of admission', h.dateOfAdmission || '—');
  addKeyValue(ctx, 'Date of delivery', h.dateOfDelivery || '—');
  addKeyValue(ctx, 'Prepared by', h.authorName || '—');

  if (h.narrative) {
    addSpacer(ctx, 6);
    addSectionHeader(ctx, 'Narrative Summary');
    addBody(ctx, h.narrative);
  }

  addSectionHeader(ctx, 'Summary of Findings');
  addBullet(ctx, `Critical findings: ${result.summary.criticalViolations}`);
  addBullet(ctx, `High-severity findings: ${result.summary.highViolations}`);
  addBullet(ctx, `Moderate findings: ${result.summary.moderateViolations}`);
  addBullet(ctx, `Sustained hypotension episodes without bedside response: ${result.summary.hypotensionEpisodes}`);
  addBullet(ctx, `Documented unattended-patient gaps: ${result.summary.unattendedGaps}`);
  addBullet(ctx, `Invasive procedures lacking documented consent or order: ${result.summary.consentScopeFlags}`);
  addBullet(ctx, `Cervical-ripening → induction interval breaches: ${result.summary.ripeningIntervalFlags}`);
  addBullet(ctx, `Category III fetal heart-rate windows: ${result.summary.catIII}`);
  addBullet(ctx, `Tachysystole windows: ${result.summary.tachysystoleWindows}`);

  // Group findings by category so the complaint reads like a structured report.
  const order = { critical: 0, high: 1, moderate: 2 } as const;
  const sorted = [...result.violations].sort((a, b) => order[a.severity] - order[b.severity] || a.t.localeCompare(b.t));

  const groups: { title: string; codes: string[] }[] = [
    { title: 'Maternal Hemodynamic Concerns', codes: ['maternal_hypotension'] },
    { title: 'Bedside Attendance and Monitoring Compliance', codes: ['unattended_patient'] },
    { title: 'Consent and Scope-of-Practice Concerns', codes: ['consent_scope'] },
    { title: 'Induction Protocol Concerns', codes: ['ripening_interval', 'miso_interval'] },
    { title: 'Oxytocin Stop-Rule Concerns', codes: ['pit_cat3', 'pit_running_cat3', 'pit_tachy', 'pit_cat2'] },
    { title: 'Misoprostol Concerns', codes: ['miso_tachy'] },
  ];

  for (const g of groups) {
    const items = sorted.filter((v) => g.codes.includes(v.ruleCode || ''));
    if (!items.length) continue;
    addSectionHeader(ctx, g.title);
    for (const v of items) renderFinding(ctx, v);
  }

  // Catch-all for any violations without a known group.
  const ungrouped = sorted.filter((v) => !groups.some((g) => g.codes.includes(v.ruleCode || '')));
  if (ungrouped.length) {
    addSectionHeader(ctx, 'Other Findings');
    for (const v of ungrouped) renderFinding(ctx, v);
  }

  if (!sorted.length) {
    addAlertBox(ctx, 'No stop-rule violations detected with the records provided. Additional records may be required for a complete review.', 'info');
  }

  addSectionHeader(ctx, 'Requested Actions');
  addBullet(ctx, 'Acknowledge receipt of this concern in writing within 7 business days.');
  addBullet(ctx, 'Conduct a root-cause analysis covering each finding above with patient-safety committee involvement.');
  addBullet(ctx, 'Provide a copy of the complete medical record (fetal monitor strips, MAR, nursing flowsheet, provider orders, consent forms) under HIPAA right of access (45 CFR 164.524) within 30 days.');
  addBullet(ctx, 'Identify corrective actions and staff education undertaken in response.');

  addSectionHeader(ctx, 'Methodology and Limitations');
  addBody(ctx,
    'Findings above were generated by an automated retrospective audit engine that compares fetal monitor tracing, medication administration, maternal vitals, and documented bedside care against published ACOG and AWHONN guidance. Each finding cites the underlying rule and the timestamped evidence. This packet is decision-support; it is not a substitute for an independent expert review and does not establish standard-of-care liability on its own.',
  );

  addFooter(ctx, 'Generated by SOUPY Audit — OB Fetal Monitoring complaint packet. Retrospective decision-support; does not replace independent expert review.');
  ctx.doc.save(filename);
}

function renderFinding(ctx: ReturnType<typeof createPDFContext>, v: StopRuleViolation) {
  addTitle(ctx, `[${v.severity.toUpperCase()}] ${new Date(v.t).toLocaleString()}`, 11);
  addKeyValue(ctx, 'Applicable rule', v.rule);
  addKeyValue(ctx, 'Observed', v.stripFinding);
  addKeyValue(ctx, 'Care delivered', v.medAction);
  addKeyValue(ctx, 'Charted response', v.chartedResponse);
  if (v.minutesToAction !== undefined) {
    addKeyValue(ctx, 'Time to corrective action',
      v.minutesToAction === null ? 'No corrective action documented' : `${v.minutesToAction} min`);
  }
  addSpacer(ctx, 4);
  addDivider(ctx);
}