import type { AuditCase, PhysicianPattern, SOUPYConfig, EvidenceChecklistItem, CodeCombinationAnalysis } from './types';

export const defaultSOUPYConfig: SOUPYConfig = {
  roles: {
    builder: 'GPT-4o',
    redteam: 'Claude 3.5',
    analyst: 'Gemini Pro',
    breaker: 'GPT-4o Mini',
  },
  executionOrder: ['builder', 'redteam', 'analyst', 'breaker'],
};

export const mockCases: AuditCase[] = [
  {
    id: '1',
    caseNumber: 'AUD-2024-001',
    patientId: 'PT-88291',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-01-15',
    dateSubmitted: '2024-01-18',
    status: 'in-review',
    assignedTo: 'John Auditor',
    cptCodes: ['99285', '99291', '99292'],
    icdCodes: ['I21.0', 'R06.02', 'E11.65'],
    claimAmount: 4850,
    consensusScore: 75,
    riskScore: {
      level: 'high',
      score: 78,
      rawScore: 82,
      percentile: 92,
      confidence: 72,
      recommendation: 'Recommend detailed review. Multiple high-value codes with documentation gaps.',
      dataCompleteness: {
        score: 72,
        present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount', 'Physician ID'],
        missing: ['Operative note', 'Critical care time log', 'Lab results'],
      },
      factors: [
        { id: 'f1', title: 'High-value ED + Critical Care combination', description: 'ED level 5 billed same day as critical care', whyItMatters: 'These codes together require clear documentation that critical care was distinct from ED evaluation', evidenceToConfirm: ['Critical care start/stop times', 'ED documentation showing transition to critical care'], weight: 25, isDeterminative: true, triggered: true },
        { id: 'f2', title: 'Multiple add-on units', description: 'Critical care add-on (99292) billed', whyItMatters: 'Additional critical care time must be clearly documented separately', evidenceToConfirm: ['Time logs showing >74 minutes of critical care', 'Activities during additional time'], weight: 20, isDeterminative: true, triggered: true },
        { id: 'f3', title: 'Weekend service date', description: 'Service rendered on a Saturday', whyItMatters: 'Weekend services have higher documentation error rates (not fraud indicator)', evidenceToConfirm: ['Staffing records', 'Attending physician confirmation'], weight: 5, isDeterminative: false, triggered: true },
        { id: 'f4', title: 'Claim amount exceeds specialty median', description: 'Total claim $4,850 vs $3,200 median for similar cases', whyItMatters: 'Higher-than-average claims warrant documentation review', evidenceToConfirm: ['Itemized billing statement', 'Documentation supporting each code'], weight: 15, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 72,
        perspectiveStatement: 'The code combination is defensible if documentation supports a genuine clinical escalation from emergency evaluation to critical care management.',
        keyInsights: [
          'STEMI presentation justifies both ED evaluation and critical care',
          'Time-based billing is appropriate if properly documented',
          'ICD codes support medical necessity for critical interventions',
        ],
        assumptions: ['ED evaluation preceded critical care', 'Patient condition genuinely deteriorated', 'Time was properly tracked'],
        violations: [
          {
            id: 'v1', code: '99291', type: 'medical-necessity', severity: 'warning',
            description: 'Critical care time documentation may be insufficient to support billing',
            regulationRef: 'CPT Guidelines §99291-99292; CMS Transmittal 1548',
            defenses: [
              { role: 'builder', strategy: 'STEMI presentation inherently requires critical care management. The clinical scenario supports time-intensive interventions.', strengths: ['Strong clinical indication', 'Life-threatening condition'], weaknesses: ['Missing explicit time documentation'], strength: 68 },
              { role: 'redteam', strategy: 'Without start/stop times, this billing cannot withstand audit scrutiny regardless of clinical merit.', strengths: ['Identifies documentation gap'], weaknesses: ['Ignores clinical context'], strength: 45 },
              { role: 'analyst', strategy: 'CMS requires contemporaneous time documentation. Retrospective attestation may be accepted with corroborating records.', strengths: ['Regulatory framework provided', 'Alternative evidence path'], weaknesses: ['Retrospective documentation weaker'], strength: 55 },
              { role: 'breaker', strategy: 'Consider whether EHR timestamp data can reconstruct critical care time intervals as supporting evidence.', strengths: ['Novel evidence approach', 'Leverages available data'], weaknesses: ['Not standard practice'], strength: 52 },
            ],
          },
          {
            id: 'v2', code: '99285', type: 'upcoding', severity: 'critical',
            description: 'ED visit level 5 requires documentation of immediate, significant threat to life or physiologic function',
            regulationRef: 'AMA CPT Professional Edition; CMS OPPS Guidelines',
            defenses: [
              { role: 'builder', strategy: 'Acute STEMI with respiratory distress clearly meets level 5 criteria for threat to life.', strengths: ['Clear clinical justification', 'ICD codes support acuity'], weaknesses: ['Documentation completeness unknown'], strength: 78 },
              { role: 'redteam', strategy: 'Level 5 is the most scrutinized ED code. Without explicit MDM documentation, downcode to 99284 is likely.', strengths: ['Realistic audit outcome prediction'], weaknesses: ['May undervalue clinical acuity'], strength: 40 },
              { role: 'analyst', strategy: 'MDM elements must be explicitly documented per 2021 E/M guidelines. Check for high-risk diagnoses and data reviewed.', strengths: ['Specific guideline reference', 'Actionable review criteria'], weaknesses: ['Requires documentation review'], strength: 60 },
              { role: 'breaker', strategy: 'The combination of I21.0 + R06.02 statistically correlates with 99285 in >90% of compliant claims. Pattern data supports the code.', strengths: ['Data-driven defense', 'Statistical backing'], weaknesses: ['Pattern ≠ individual compliance'], strength: 55 },
            ],
          },
        ],
        overallAssessment: 'Defensible case with documentation improvements needed. The clinical scenario strongly supports the codes billed, but documentation gaps create audit vulnerability.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 85,
        perspectiveStatement: 'Multiple documentation gaps create significant audit exposure. The billing pattern raises questions that require explicit documentation to resolve.',
        keyInsights: [
          'No critical care time logs found in available records',
          'ED Level 5 + Critical Care same-day billing is a known audit target',
          'Missing documentation for medical decision-making complexity',
        ],
        assumptions: ['Available documentation represents complete record', 'Standard audit criteria will be applied'],
        violations: [
          {
            id: 'v3', code: '99291', type: 'medical-necessity', severity: 'critical',
            description: 'Critical care billing requires contemporaneous time documentation — none found',
            regulationRef: 'CMS IOM Pub 100-04, Ch.12, §30.6.12',
            defenses: [
              { role: 'builder', strategy: 'Clinical acuity of STEMI makes critical care self-evident.', strengths: ['Strong clinical case'], weaknesses: ['Self-evidence insufficient for billing'], strength: 35 },
              { role: 'redteam', strategy: 'This violation is clear-cut. Without time documentation, appeal success rate is <20%.', strengths: ['Honest assessment', 'Prepares for likely outcome'], weaknesses: ['No constructive defense offered'], strength: 20 },
              { role: 'analyst', strategy: 'Seek nursing notes, medication administration records, and EHR audit logs as alternative time evidence.', strengths: ['Identifies alternative evidence sources'], weaknesses: ['Secondary evidence may not satisfy auditors'], strength: 48 },
              { role: 'breaker', strategy: 'Challenge whether the audit criteria is being applied retroactively to a standard that wasn\'t in effect at time of service.', strengths: ['Procedural defense angle'], weaknesses: ['Risky strategy if criteria was current'], strength: 30 },
            ],
          },
        ],
        overallAssessment: 'High audit risk. Recommend requesting complete documentation before making determination. Key gaps in time-based billing support.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 79,
        perspectiveStatement: 'Regulatory framework analysis indicates this code combination requires specific documentation elements that are partially present in the available record.',
        keyInsights: [
          'CMS 2021 E/M guidelines apply — MDM-based scoring required',
          'Critical care time exclusions for separately billable procedures must be documented',
          'Code combination has 34% audit trigger rate nationally',
        ],
        assumptions: ['2021 E/M guidelines in effect', 'Standard MAC audit criteria apply', 'National benchmarks are relevant'],
        violations: [
          {
            id: 'v4', code: '99292', type: 'unbundling', severity: 'warning',
            description: 'Add-on critical care time may overlap with separately billed procedures',
            regulationRef: 'CPT Appendix C; CMS NCCI Edits',
            defenses: [
              { role: 'builder', strategy: 'Multiple interventions during STEMI management justify extended critical care beyond initial 74 minutes.', strengths: ['Clinical justification', 'Complex case'], weaknesses: ['Must prove >74 min of qualifying time'], strength: 62 },
              { role: 'redteam', strategy: 'Burden of proof is on provider. Without explicit time exclusion documentation, this code will be denied.', strengths: ['Clear audit standard'], weaknesses: ['Assumes worst case'], strength: 38 },
              { role: 'analyst', strategy: 'Reconstruct timeline from medication administration records, vital sign timestamps, and procedure logs to calculate qualifying time.', strengths: ['Systematic approach', 'Multiple evidence sources'], weaknesses: ['Time-intensive reconstruction'], strength: 65 },
              { role: 'breaker', strategy: 'Consider whether the clinical complexity itself serves as evidence — STEMI management is inherently >74 minutes.', strengths: ['Appeals to clinical common sense'], weaknesses: ['Not documentation-based'], strength: 42 },
            ],
          },
        ],
        overallAssessment: 'Mixed compliance picture. The regulatory framework supports the clinical scenario, but specific documentation requirements are only partially met.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 65,
        perspectiveStatement: 'The traditional audit lens may be missing the forest for the trees. This billing pattern is clinically appropriate — the question is whether documentation practices match clinical reality.',
        keyInsights: [
          'Documentation standards may not reflect actual clinical workflow',
          'EHR design contributes to documentation gaps (system issue, not provider issue)',
          'Similar cases in peer institutions show 78% approval rate with comparable documentation',
        ],
        assumptions: ['Documentation gaps ≠ clinical gaps', 'EHR limitations are systemic', 'Peer comparison is relevant'],
        violations: [],
        overallAssessment: 'Consider systemic factors before individual case determination. Documentation improvement recommendations may be more appropriate than denial.',
      },
    ],
    metadata: {
      dayOfWeek: 'Saturday',
      timeOfDay: '22:30',
      anesthesiaType: 'None',
      patientObesity: false,
      understaffing: true,
      errorsFound: 3,
      upchargeAmount: 1200,
      procedureDuration: 185,
    },
  },
  {
    id: '2',
    caseNumber: 'AUD-2024-002',
    patientId: 'PT-66103',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-01-22',
    dateSubmitted: '2024-01-25',
    status: 'pending',
    cptCodes: ['99285', '99291'],
    icdCodes: ['J96.01', 'R65.20'],
    claimAmount: 3600,
    consensusScore: 88,
    riskScore: {
      level: 'medium',
      score: 55,
      rawScore: 55,
      percentile: 68,
      confidence: 80,
      recommendation: 'Standard review. Code combination is common for critical presentations.',
      dataCompleteness: { score: 80, present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount', 'Physician ID', 'Time documentation'], missing: ['Operative note', 'Lab results'] },
      factors: [
        { id: 'f5', title: 'ED + Critical Care combination', description: 'Common but audited combination', whyItMatters: 'Requires clear clinical escalation documentation', evidenceToConfirm: ['Time logs', 'Clinical transition notes'], weight: 20, isDeterminative: true, triggered: true },
        { id: 'f6', title: 'Claim within normal range', description: 'Amount is within 1 SD of specialty median', whyItMatters: 'Lower statistical outlier risk', evidenceToConfirm: [], weight: 5, isDeterminative: false, triggered: false },
      ],
    },
    analyses: [],
    metadata: { dayOfWeek: 'Monday', timeOfDay: '14:15', anesthesiaType: 'None', patientObesity: true, understaffing: false, errorsFound: 1, upchargeAmount: 400, procedureDuration: 120 },
  },
  {
    id: '3',
    caseNumber: 'AUD-2024-003',
    patientId: 'PT-44290',
    physicianId: 'DR-7722',
    physicianName: 'Dr. James Park',
    dateOfService: '2024-02-03',
    dateSubmitted: '2024-02-06',
    status: 'approved',
    assignedTo: 'Jane Reviewer',
    cptCodes: ['43235', '43239'],
    icdCodes: ['K21.0', 'K29.70'],
    claimAmount: 2100,
    consensusScore: 95,
    riskScore: {
      level: 'low',
      score: 25,
      rawScore: 25,
      percentile: 22,
      confidence: 90,
      recommendation: 'Low risk. Standard GI procedure with appropriate coding.',
      dataCompleteness: { score: 90, present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pathology report', 'Physician ID', 'Service metadata'], missing: ['Prior authorization'] },
      factors: [
        { id: 'f7', title: 'Standard procedure combination', description: 'Diagnostic + biopsy is common', whyItMatters: 'Typical billing pattern for GI procedures', evidenceToConfirm: [], weight: 5, isDeterminative: false, triggered: false },
      ],
    },
    analyses: [],
    decision: { outcome: 'approved', reasoning: 'All documentation supports codes billed. Pathology report confirms biopsy necessity.', auditor: 'Jane Reviewer', timestamp: '2024-02-08T10:30:00Z', overrides: [] },
    metadata: { dayOfWeek: 'Wednesday', timeOfDay: '09:00', anesthesiaType: 'Conscious Sedation', patientObesity: false, understaffing: false, errorsFound: 0, upchargeAmount: 0, procedureDuration: 45 },
  },
  {
    id: '4',
    caseNumber: 'AUD-2024-004',
    patientId: 'PT-55120',
    physicianId: 'DR-7722',
    physicianName: 'Dr. James Park',
    dateOfService: '2024-02-10',
    dateSubmitted: '2024-02-13',
    status: 'rejected',
    assignedTo: 'John Auditor',
    cptCodes: ['29880', '29881'],
    icdCodes: ['M23.21', 'M17.11'],
    claimAmount: 5200,
    consensusScore: 40,
    riskScore: {
      level: 'critical',
      score: 91,
      rawScore: 98,
      percentile: 98,
      confidence: 85,
      recommendation: 'High risk of overbilling. Both meniscectomy codes billed for same knee requires strong justification.',
      dataCompleteness: { score: 85, present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pre-op imaging', 'Physician ID', 'Service metadata'], missing: ['Distinct compartment documentation'] },
      factors: [
        { id: 'f8', title: 'Duplicate meniscectomy codes', description: '29880 and 29881 billed together', whyItMatters: '29880 includes both compartments — billing 29881 additionally suggests unbundling', evidenceToConfirm: ['Operative note showing distinct work in separate compartments', 'Medical necessity for both procedures'], weight: 35, isDeterminative: true, triggered: true },
        { id: 'f9', title: 'High claim amount', description: '$5,200 is 2.1x specialty median', whyItMatters: 'Significant financial outlier', evidenceToConfirm: ['Itemized billing', 'Justification for each code'], weight: 20, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [],
    decision: { outcome: 'rejected', reasoning: 'Operative note does not support billing both 29880 and 29881. 29880 includes medial AND lateral meniscectomy. Recommend rebilling with 29880 only.', auditor: 'John Auditor', timestamp: '2024-02-15T14:00:00Z', overrides: [] },
    metadata: { dayOfWeek: 'Friday', timeOfDay: '07:30', anesthesiaType: 'General', patientObesity: true, understaffing: false, errorsFound: 2, upchargeAmount: 2600, procedureDuration: 90 },
  },
  {
    id: '5',
    caseNumber: 'AUD-2024-005',
    patientId: 'PT-77443',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-02-17',
    dateSubmitted: '2024-02-20',
    status: 'pending',
    cptCodes: ['99285', '99291', '99292'],
    icdCodes: ['I46.9', 'J96.00'],
    claimAmount: 5100,
    consensusScore: 70,
    riskScore: {
      level: 'high',
      score: 80,
      rawScore: 85,
      percentile: 94,
      confidence: 68,
      recommendation: 'Pattern detected: Third case from same physician with identical code combination. Recommend pattern analysis.',
      dataCompleteness: { score: 68, present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount'], missing: ['Critical care time log', 'Operative note', 'Lab results', 'Nursing notes'] },
      factors: [
        { id: 'f10', title: 'Repeat code pattern', description: 'Same physician, same CPT combination (3rd occurrence)', whyItMatters: 'Recurring patterns may indicate systemic billing practices', evidenceToConfirm: ['Pattern analysis review', 'Peer comparison'], weight: 30, isDeterminative: true, triggered: true },
        { id: 'f11', title: 'Off-hours service', description: 'Service at 03:15 AM', whyItMatters: 'Off-hours services have higher documentation error likelihood', evidenceToConfirm: ['Staffing records', 'Attending attestation'], weight: 5, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [],
    metadata: { dayOfWeek: 'Sunday', timeOfDay: '03:15', anesthesiaType: 'None', patientObesity: false, understaffing: true, errorsFound: 4, upchargeAmount: 1800, procedureDuration: 210 },
  },
  // ============================================================
  // REALISTIC SURGICAL TEST CASES
  // Based on common audit flags seen in OR environments
  // ============================================================
  {
    id: '6',
    caseNumber: 'AUD-2024-006',
    patientId: 'PT-33104',
    physicianId: 'DR-9915',
    physicianName: 'Dr. Richard Tran',
    dateOfService: '2024-03-04',
    dateSubmitted: '2024-03-07',
    status: 'in-review',
    assignedTo: 'John Auditor',
    cptCodes: ['27447', '20930', '27380'],
    icdCodes: ['M17.11', 'M17.12', 'M80.051A'],
    claimAmount: 18750,
    consensusScore: 42,
    riskScore: {
      level: 'critical',
      score: 88,
      rawScore: 94,
      percentile: 96,
      confidence: 78,
      recommendation: 'High-value orthopedic case with potential unbundling. Total knee arthroplasty billed with bone graft and additional suture that may be included in primary procedure.',
      dataCompleteness: {
        score: 65,
        present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pre-op imaging', 'Physician ID', 'Anesthesia record'],
        missing: ['Bone graft source documentation', 'Medical necessity for 27380', 'Implant log with lot numbers'],
      },
      factors: [
        { id: 'f12', title: 'Bone graft unbundling from TKA', description: '20930 (morselized bone graft) billed separately from 27447 (TKA)', whyItMatters: 'Bone graft is typically included in TKA reimbursement unless a separate, distinct graft site is used', evidenceToConfirm: ['Separate incision documentation', 'Distinct graft harvest site operative note', 'Medical necessity for structural allograft'], weight: 35, isDeterminative: true, triggered: true },
        { id: 'f13', title: 'Additional suture code with arthroplasty', description: '27380 (suture of infrapatellar tendon) billed with TKA', whyItMatters: 'Tendon repair during arthroplasty is typically included unless a separate, pre-existing condition required repair', evidenceToConfirm: ['Pre-operative imaging showing tendon pathology', 'Separate diagnosis supporting repair', 'Distinct operative report section'], weight: 25, isDeterminative: true, triggered: true },
        { id: 'f14', title: 'Claim 4.2x specialty median', description: '$18,750 vs $4,500 median for TKA', whyItMatters: 'Extreme financial outlier — most TKA claims don\'t include add-on codes', evidenceToConfirm: ['Itemized billing', 'Medical necessity for each add-on'], weight: 20, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 55,
        perspectiveStatement: 'The additional codes may be justified if the patient had pre-existing bone deficiency requiring structural grafting and documented tendon pathology separate from the arthroplasty.',
        keyInsights: [
          'Osteoporotic fracture code (M80.051A) supports possible bone deficiency requiring graft',
          'If graft was harvested from a separate site, 20930 is independently billable',
          'Tendon repair is defensible if pre-op MRI shows existing tear',
        ],
        assumptions: ['Bone graft was from distinct site', 'Tendon pathology pre-existed the surgery', 'Operative note contains separate sections for each procedure'],
        violations: [
          {
            id: 'v5', code: '20930', type: 'unbundling', severity: 'critical',
            description: 'Bone graft (morselized allograft) may be included in TKA reimbursement — separate billing requires distinct documentation',
            regulationRef: 'CMS NCCI Policy Manual Ch.4 §D; CPT Appendix A Modifier Guidelines',
            defenses: [
              { role: 'builder', strategy: 'Osteoporotic bone (M80.051A) creates legitimate need for structural allograft beyond what\'s included in standard TKA.', strengths: ['ICD code supports bone deficiency', 'Clinical rationale present'], weaknesses: ['Must prove graft was not part of standard TKA technique'], strength: 58 },
              { role: 'redteam', strategy: 'Without separate incision documentation and distinct graft site, this is textbook unbundling. 85% denial rate on audit.', strengths: ['Clear NCCI edit violation', 'Strong statistical backing'], weaknesses: ['Doesn\'t consider clinical complexity'], strength: 30 },
              { role: 'analyst', strategy: 'Check implant log — if allograft was ordered separately and has its own lot number, it supports distinct billing.', strengths: ['Objective evidence approach', 'Verifiable'], weaknesses: ['Implant log alone may not be sufficient'], strength: 50 },
              { role: 'breaker', strategy: 'Challenge the NCCI edit — modifier 59 (distinct procedural service) may apply if graft was used to fill a separate bone defect, not the arthroplasty bed.', strengths: ['Regulatory pathway exists', 'Modifier defense'], weaknesses: ['Modifier 59 is heavily scrutinized'], strength: 45 },
            ],
          },
        ],
        overallAssessment: 'Potentially defensible but requires strong documentation of separate bone deficiency and distinct surgical site. Without it, recommend rebilling TKA alone.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 90,
        perspectiveStatement: 'This is a classic unbundling pattern. The surgeon added extra codes to inflate the claim — both add-ons are typically included in TKA reimbursement.',
        keyInsights: [
          'National NCCI edits pair 20930 with 27447 — modifier 59 override required and heavily audited',
          '27380 is almost never billed separately with TKA — 99.2% of TKA claims don\'t include it',
          'This physician has 3 other TKA cases with similar add-on patterns in the last quarter',
        ],
        assumptions: ['Standard NCCI edits apply', 'No modifier 59 documentation present', 'Pattern suggests systematic behavior'],
        violations: [
          {
            id: 'v6', code: '27380', type: 'unbundling', severity: 'critical',
            description: 'Infrapatellar tendon suture is integral to TKA closure — billing separately is unbundling unless pre-existing tear is documented',
            regulationRef: 'CMS NCCI Policy Manual Ch.1 §E; AMA CPT Assistant March 2019',
            defenses: [
              { role: 'builder', strategy: 'Pre-existing tendon tear documented on pre-op MRI would justify separate billing.', strengths: ['Clear documentation path'], weaknesses: ['No MRI in current record'], strength: 25 },
              { role: 'redteam', strategy: 'Tendon repair during TKA is standard technique, not a separate procedure. This code should not have been submitted.', strengths: ['Strong regulatory basis', 'Statistical backing'], weaknesses: ['Absolute stance'], strength: 15 },
              { role: 'analyst', strategy: 'Request pre-op imaging and compare to post-op note. If tendon was intact pre-op, 27380 is unbundled.', strengths: ['Evidence-based determination'], weaknesses: ['Requires additional records'], strength: 40 },
              { role: 'breaker', strategy: 'Consider whether the surgeon documented an intraoperative complication (tendon avulsion during exposure) — this would change the coding entirely.', strengths: ['Considers unexpected clinical events'], weaknesses: ['If true, should have different ICD code'], strength: 35 },
            ],
          },
        ],
        overallAssessment: 'High confidence this is unbundled billing. Recommend denial of 20930 and 27380, approve 27447 alone. Flag physician for pattern review.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 75,
        perspectiveStatement: 'NCCI edits are clear — both add-on codes have column 1/column 2 relationships with TKA. However, modifier pathways exist if documentation supports distinct services.',
        keyInsights: [
          'NCCI column 1/column 2 edit: 27447 bundles 20930 unless modifier 59 or XE/XS/XP/XU applies',
          'CMS allows separate bone graft billing only when: (1) distinct site, (2) distinct diagnosis, (3) distinct session',
          'Implant cost analysis shows allograft invoice of $2,800 — suggesting actual graft was used',
        ],
        assumptions: ['NCCI edits are correctly applied', 'Modifier documentation burden is on provider', 'Implant invoice is authentic'],
        violations: [],
        overallAssessment: 'The implant invoice suggests real allograft was used, which partially supports 20930. Request complete documentation before determination. Deny 27380 pending evidence of pre-existing pathology.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 60,
        perspectiveStatement: 'Before labeling this as fraud, consider that complex orthopedic cases in osteoporotic patients genuinely require additional procedures. The billing may reflect real clinical complexity.',
        keyInsights: [
          'Osteoporotic patients have 3x higher complication rates in TKA — additional procedures are clinically expected',
          'Teaching hospitals report higher add-on code rates due to resident involvement and case complexity',
          'Surgeon may be documenting real work that peers routinely under-code',
        ],
        assumptions: ['Clinical complexity was real', 'Documentation practices vary by institution', 'Under-coding is as problematic as over-coding'],
        violations: [],
        overallAssessment: 'Recommend requesting full operative note and implant records before determination. Pattern analysis alone is insufficient — each case must be evaluated on its documentation.',
      },
    ],
    metadata: { dayOfWeek: 'Monday', timeOfDay: '07:15', anesthesiaType: 'General', patientObesity: true, understaffing: false, errorsFound: 2, upchargeAmount: 14250, procedureDuration: 165 },
  },
  {
    id: '7',
    caseNumber: 'AUD-2024-007',
    patientId: 'PT-19887',
    physicianId: 'DR-5533',
    physicianName: 'Dr. Anika Patel',
    dateOfService: '2024-03-11',
    dateSubmitted: '2024-03-14',
    status: 'in-review',
    assignedTo: 'Jane Reviewer',
    cptCodes: ['22612', '22614', '22842', '20930', '63047'],
    icdCodes: ['M43.16', 'M48.06', 'G89.29', 'M54.5'],
    claimAmount: 42300,
    consensusScore: 35,
    riskScore: {
      level: 'critical',
      score: 93,
      rawScore: 97,
      percentile: 99,
      confidence: 82,
      recommendation: 'Extremely high-value spine fusion case with 5 CPT codes. Multiple potential unbundling and modifier issues. Mandatory detailed review.',
      dataCompleteness: {
        score: 58,
        present: ['CPT codes', 'ICD-10 codes', 'Operative note (partial)', 'Pre-op imaging', 'Anesthesia record'],
        missing: ['Complete operative note', 'Fluoroscopy images', 'Implant manifest with lot numbers', 'Medical necessity letter', 'Pre-authorization'],
      },
      factors: [
        { id: 'f15', title: 'Multi-level spine fusion with decompression', description: '5 CPT codes for single spine session', whyItMatters: 'Spine surgery is the #1 audited surgical specialty — multi-code submissions are automatically flagged', evidenceToConfirm: ['Complete op note with level-by-level documentation', 'Fluoroscopy confirmation of levels treated', 'Medical necessity for each procedure'], weight: 30, isDeterminative: true, triggered: true },
        { id: 'f16', title: 'Add-on fusion level', description: '22614 billed as additional segment', whyItMatters: 'Each additional level must be independently documented with fluoroscopic confirmation', evidenceToConfirm: ['Intraoperative fluoroscopy for each level', 'Separate operative steps per level'], weight: 25, isDeterminative: true, triggered: true },
        { id: 'f17', title: 'Claim amount extreme outlier', description: '$42,300 is 6.8x specialty median', whyItMatters: 'Top 1% of spine surgery claims by dollar amount', evidenceToConfirm: ['Itemized implant costs', 'Justification for instrumentation extent'], weight: 15, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 48,
        perspectiveStatement: 'Multi-level spine fusion with decompression is a legitimate procedure combination for spondylolisthesis with stenosis, but every code must stand on its own documentation.',
        keyInsights: [
          'M43.16 (lumbar spondylolisthesis) + M48.06 (lumbar stenosis) creates medical necessity for fusion + decompression',
          'Chronic pain diagnosis (G89.29) supports failure of conservative treatment',
          'The procedure codes are clinically coherent — this IS what a complex spine case looks like',
        ],
        assumptions: ['All 5 procedures were actually performed', 'Each level was separately documented', 'Conservative treatment was attempted first'],
        violations: [
          {
            id: 'v7', code: '63047', type: 'unbundling', severity: 'warning',
            description: 'Laminectomy (63047) with posterior fusion (22612) — some payers consider decompression included in fusion approach',
            regulationRef: 'CMS NCCI Ch.4; AMA CPT Assistant October 2020',
            defenses: [
              { role: 'builder', strategy: 'Decompression was the primary indication — fusion was added for instability. Sequence matters for billing.', strengths: ['Clinical logic supports separate billing', 'AMA guidance supports this'], weaknesses: ['Some MACs disagree'], strength: 62 },
              { role: 'redteam', strategy: 'Many payers bundle 63047 into 22612 when performed at same level. Without modifier documentation, expect denial.', strengths: ['Payer-specific reality'], weaknesses: ['Not universally applied'], strength: 35 },
              { role: 'analyst', strategy: 'Check if decompression and fusion were at same or different levels. Different levels = clearly separate. Same level = modifier 59 required.', strengths: ['Precise determination criteria'], weaknesses: ['Requires detailed op note review'], strength: 55 },
              { role: 'breaker', strategy: 'The real question is whether the stenosis was at the fusion level or adjacent. Adjacent decompression is universally accepted as separate.', strengths: ['Reframes the analysis'], weaknesses: ['Requires imaging correlation'], strength: 50 },
            ],
          },
        ],
        overallAssessment: 'Clinically coherent but documentation-heavy case. Each of the 5 codes needs independent justification. Request complete operative note before determination.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 88,
        perspectiveStatement: 'This $42K claim is exactly the type of case that generates recovery dollars. Multiple bundling vulnerabilities and incomplete documentation make this highly actionable.',
        keyInsights: [
          'Only partial operative note available — incomplete documentation is itself a red flag',
          'Bone graft (20930) billed separately from fusion is a known audit target',
          'This surgeon\'s spine cases average 3.2 CPT codes vs. peer average of 1.8',
        ],
        assumptions: ['Incomplete documentation = unsupported codes', 'Peer benchmarks are meaningful', 'Pattern is systemic'],
        violations: [
          {
            id: 'v8', code: '22842', type: 'modifier-misuse', severity: 'critical',
            description: 'Posterior segmental instrumentation (22842) requires documentation of specific levels instrumented with implant details',
            regulationRef: 'CMS LCD L35000; NASS Coding Guidelines 2023',
            defenses: [
              { role: 'builder', strategy: 'Instrumentation is standard with fusion — the code is expected and appropriate if implants are documented.', strengths: ['Clinically appropriate'], weaknesses: ['Implant manifest missing'], strength: 40 },
              { role: 'redteam', strategy: 'No implant manifest, no lot numbers, no fluoroscopy confirmation. This code cannot survive audit.', strengths: ['Documentation gap is clear'], weaknesses: ['Doesn\'t mean procedure wasn\'t done'], strength: 20 },
              { role: 'analyst', strategy: 'Request implant manifest from OR supply chain. If screws/rods are documented with lot numbers, code is defensible.', strengths: ['Practical evidence path'], weaknesses: ['Supply chain records may not be in chart'], strength: 52 },
              { role: 'breaker', strategy: 'Post-op X-ray would show instrumentation in place — this is objective proof regardless of documentation practices.', strengths: ['Undeniable physical evidence'], weaknesses: ['Doesn\'t prove medical necessity'], strength: 48 },
            ],
          },
        ],
        overallAssessment: 'Multiple unsupported codes. Recommend denying 20930, 22842, and 63047 pending complete documentation. Approve 22612 + 22614 if op note supports multi-level fusion.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 72,
        perspectiveStatement: 'Complex spine cases legitimately generate high code counts. The issue is not the number of codes but whether each is independently documented.',
        keyInsights: [
          'NASS 2023 guidelines support 4-5 CPT codes for multi-level fusion with decompression',
          'Average implant cost for 2-level posterior fusion is $12,000-$18,000 — aligns with claim',
          'Incomplete operative note is the single biggest vulnerability',
        ],
        assumptions: ['NASS guidelines are the standard of care', 'Implant costs are consistent with procedure', 'Op note completion is provider responsibility'],
        violations: [],
        overallAssessment: 'Request complete operative note and implant manifest. If documentation is complete, this case is likely compliant. If documentation remains incomplete, deny add-on codes.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 55,
        perspectiveStatement: 'Spine surgery billing complexity is a systemic problem — the coding rules don\'t match how surgeons actually work. This case may be a documentation failure, not a billing failure.',
        keyInsights: [
          'Surgeons perform these procedures fluidly — separate coding for each step is an artificial construct',
          'Teaching hospitals systematically under-document due to resident handoff issues',
          'The "partial operative note" may be a dictation delay, not a missing document',
        ],
        assumptions: ['Documentation will be completed', 'Clinical work was performed', 'System issues contribute to gaps'],
        violations: [],
        overallAssessment: 'Hold determination for 30 days to allow documentation completion. If op note is completed with level-by-level detail, approve all codes. Pattern analysis should wait for complete data.',
      },
    ],
    metadata: { dayOfWeek: 'Tuesday', timeOfDay: '06:45', anesthesiaType: 'General', patientObesity: false, understaffing: false, errorsFound: 3, upchargeAmount: 36100, procedureDuration: 340 },
  },
  {
    id: '8',
    caseNumber: 'AUD-2024-008',
    patientId: 'PT-82210',
    physicianId: 'DR-3318',
    physicianName: 'Dr. Marcus Webb',
    dateOfService: '2024-03-18',
    dateSubmitted: '2024-03-21',
    status: 'pending',
    cptCodes: ['44204', '44180'],
    icdCodes: ['K57.20', 'K65.1', 'K63.1'],
    claimAmount: 9800,
    consensusScore: 58,
    riskScore: {
      level: 'high',
      score: 72,
      rawScore: 76,
      percentile: 88,
      confidence: 74,
      recommendation: 'Laparoscopic colectomy with colostomy creation. Review for potential upcoding if procedure was converted to open.',
      dataCompleteness: {
        score: 70,
        present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Anesthesia record', 'Physician ID', 'Pathology report'],
        missing: ['Conversion documentation', 'Intraoperative photos', 'Post-op imaging'],
      },
      factors: [
        { id: 'f18', title: 'Lap colectomy + colostomy combination', description: '44204 (lap colectomy) with 44180 (lap colostomy)', whyItMatters: 'Colostomy creation is often included in colectomy reimbursement depending on payer', evidenceToConfirm: ['Documentation showing colostomy was not part of planned colectomy', 'Medical necessity for diversion'], weight: 25, isDeterminative: true, triggered: true },
        { id: 'f19', title: 'Possible open conversion undercoding', description: 'Anesthesia time suggests possible lap-to-open conversion', whyItMatters: 'If converted to open, CPT codes should change — lap codes for an open procedure is miscoding', evidenceToConfirm: ['Operative note conversion documentation', 'Anesthesia record timeline'], weight: 30, isDeterminative: true, triggered: true },
        { id: 'f20', title: 'Peritonitis + perforation diagnoses', description: 'K65.1 (peritonitis) and K63.1 (perforation) with diverticulosis', whyItMatters: 'Emergency surgical presentation — higher complexity but also higher scrutiny', evidenceToConfirm: ['ED records showing emergent presentation', 'CT imaging'], weight: 10, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 62,
        perspectiveStatement: 'Emergency laparoscopic colectomy with Hartmann\'s procedure (colostomy) is clinically appropriate for perforated diverticulitis with peritonitis.',
        keyInsights: [
          'K57.20 + K65.1 + K63.1 = perforated diverticulitis with peritonitis — surgical emergency',
          'Hartmann\'s procedure (resection + colostomy) is standard of care for this presentation',
          'If truly completed laparoscopically, this represents advanced surgical skill — NOT a red flag',
        ],
        assumptions: ['Procedure was genuinely completed laparoscopically', 'No conversion occurred', 'Colostomy was medically necessary (not elective)'],
        violations: [],
        overallAssessment: 'If operative note confirms laparoscopic completion, billing is appropriate. The anesthesia time discrepancy needs investigation — could indicate conversion.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 82,
        perspectiveStatement: 'The anesthesia record tells a different story than the CPT codes. 4.5-hour anesthesia time for a laparoscopic procedure that typically takes 2-3 hours suggests conversion to open.',
        keyInsights: [
          'Anesthesia time of 270 minutes is in the 95th percentile for laparoscopic colectomy',
          'If converted to open, correct codes would be 44140 + 44143 (lower reimbursement)',
          'Laparoscopic codes reimburse 15-25% higher than open equivalents — conversion upcoding is a known pattern',
        ],
        assumptions: ['Anesthesia time is accurate', 'Prolonged time indicates surgical difficulty', 'Conversion is more likely than not'],
        violations: [
          {
            id: 'v9', code: '44204', type: 'upcoding', severity: 'critical',
            description: 'Possible lap-to-open conversion not reflected in CPT codes — billing laparoscopic codes for open procedure is upcoding',
            regulationRef: 'AMA CPT Guidelines; CMS MLN Matters MM6740',
            defenses: [
              { role: 'builder', strategy: 'Some surgeons are genuinely faster laparoscopically in emergencies. Extended time could reflect adhesion lysis or washout, not conversion.', strengths: ['Clinical variability exists'], weaknesses: ['Statistical outlier needs explanation'], strength: 45 },
              { role: 'redteam', strategy: 'Request intraoperative photos showing laparoscopic view throughout. Without them, the time data suggests conversion.', strengths: ['Objective evidence standard'], weaknesses: ['Not all surgeons take photos'], strength: 25 },
              { role: 'analyst', strategy: 'Cross-reference anesthesia record for trocar removal time vs. incision closure time. Open conversion has distinct timeline signatures.', strengths: ['Forensic approach'], weaknesses: ['Requires detailed anesthesia record'], strength: 50 },
              { role: 'breaker', strategy: 'Check if the surgeon has a pattern of long laparoscopic cases — some surgeons are methodical but genuinely complete lap. Peer comparison by surgeon, not by procedure.', strengths: ['Individual practice pattern context'], weaknesses: ['Small sample size per surgeon'], strength: 42 },
            ],
          },
        ],
        overallAssessment: 'High suspicion of conversion upcoding. Request intraoperative documentation, anesthesia narrative, and trocar count before determination.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 70,
        perspectiveStatement: 'The anesthesia time anomaly is the central question. Everything else in this case is clinically coherent.',
        keyInsights: [
          'Mean anesthesia time for lap colectomy with colostomy: 180 min. This case: 270 min (1.5x mean)',
          'Peritonitis cases have longer OR times due to washout — 270 min may be within range for complicated cases',
          'NSQIP data shows perforated diverticulitis lap colectomy mean time of 210 min with SD of 65 min — 270 min is 0.92 SD above mean',
        ],
        assumptions: ['NSQIP benchmarks are applicable', 'Peritonitis adds operative time', 'Statistical analysis is appropriate'],
        violations: [],
        overallAssessment: 'Anesthesia time is elevated but within statistical range for complicated cases. Not sufficient alone to indicate conversion. Request operative note details on approach.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 58,
        perspectiveStatement: 'We\'re so focused on the conversion question that we\'re missing the real issue: was the colostomy truly a separate procedure or part of the colectomy?',
        keyInsights: [
          'Many payers bundle colostomy creation into colectomy — the 44180 code may be the real issue',
          'Hartmann\'s procedure is by definition colectomy + colostomy — billing both may be double-dipping',
          'The conversion question may be a red herring distraction from straightforward unbundling',
        ],
        assumptions: ['Payer-specific rules matter more than AMA guidelines here', 'Hartmann\'s is a single procedure conceptually'],
        violations: [],
        overallAssessment: 'Check payer-specific bundling rules for 44204 + 44180. The conversion question needs operative note review, but the unbundling question can be resolved with payer policy alone.',
      },
    ],
    metadata: { dayOfWeek: 'Wednesday', timeOfDay: '02:30', anesthesiaType: 'General', patientObesity: true, understaffing: true, errorsFound: 2, upchargeAmount: 3200, procedureDuration: 270 },
  },
  {
    id: '9',
    caseNumber: 'AUD-2024-009',
    patientId: 'PT-45001',
    physicianId: 'DR-9915',
    physicianName: 'Dr. Richard Tran',
    dateOfService: '2024-03-25',
    dateSubmitted: '2024-03-28',
    status: 'pending',
    cptCodes: ['27130', '27236'],
    icdCodes: ['S72.001A', 'W19.XXXA', 'M80.052A'],
    claimAmount: 14200,
    consensusScore: 50,
    riskScore: {
      level: 'high',
      score: 76,
      rawScore: 80,
      percentile: 90,
      confidence: 70,
      recommendation: 'Total hip arthroplasty billed with ORIF of femoral fracture — unusual combination. Verify whether both procedures were performed or if THA addressed the fracture.',
      dataCompleteness: {
        score: 72,
        present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pre-op imaging', 'Anesthesia record', 'Physician ID'],
        missing: ['Intraoperative fluoroscopy', 'Implant manifest', 'Post-op X-ray report'],
      },
      factors: [
        { id: 'f21', title: 'THA + ORIF same session', description: '27130 (THA) and 27236 (ORIF femoral fracture) billed together', whyItMatters: 'If THA was performed TO TREAT the fracture, ORIF is not separately billable. If fracture required fixation BEFORE THA could be performed, both are justified.', evidenceToConfirm: ['Operative note describing sequence', 'Pre-op imaging showing fracture pattern', 'Documentation of why both were necessary'], weight: 35, isDeterminative: true, triggered: true },
        { id: 'f22', title: 'Same physician repeat pattern', description: 'Second high-value orthopedic case from DR-9915 this month', whyItMatters: 'Pattern of high add-on code usage from same surgeon warrants cross-case analysis', evidenceToConfirm: ['Compare to AUD-2024-006', 'Peer benchmark analysis'], weight: 20, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 60,
        perspectiveStatement: 'A periprosthetic-pattern fracture in an osteoporotic patient may genuinely require both ORIF of the fracture and THA for the destroyed joint — these are distinct procedures.',
        keyInsights: [
          'S72.001A (femoral neck fracture) + M80.052A (osteoporosis) = classic fracture pattern',
          'If fracture extends below the lesser trochanter, ORIF of the shaft + THA of the joint is standard',
          'Intraoperative imaging is critical — fracture pattern determines if both codes are justified',
        ],
        assumptions: ['Fracture pattern required both procedures', 'Sequential approach was documented', 'Distinct anatomic regions were treated'],
        violations: [],
        overallAssessment: 'Defensible if fracture pattern extends beyond the hip joint. Request pre-op CT or intraoperative fluoroscopy to confirm fracture extent.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 84,
        perspectiveStatement: 'THA for femoral neck fracture IS the treatment — billing ORIF separately suggests the surgeon is double-billing for a single procedure.',
        keyInsights: [
          'Standard of care for displaced femoral neck fracture in elderly is THA or hemiarthroplasty — NOT THA + ORIF',
          'ORIF is an alternative TO THA, not an addition',
          'Same surgeon (DR-9915) had a similar unbundling flag on AUD-2024-006 — emerging pattern',
        ],
        assumptions: ['THA treats the fracture', 'ORIF was not separately necessary', 'Pattern is intentional'],
        violations: [
          {
            id: 'v10', code: '27236', type: 'unbundling', severity: 'critical',
            description: 'ORIF of femoral fracture may be included in THA when THA is performed as fracture treatment',
            regulationRef: 'CMS NCCI Policy Manual Ch.4; AAOS Coding Guidelines',
            defenses: [
              { role: 'builder', strategy: 'If fracture had a subtrochanteric extension, ORIF of the shaft is distinct from THA of the joint.', strengths: ['Anatomic distinction'], weaknesses: ['Must prove with imaging'], strength: 55 },
              { role: 'redteam', strategy: 'Femoral neck fracture treated with THA = one procedure, one code. Period.', strengths: ['Simple, defensible position'], weaknesses: ['Oversimplifies complex fractures'], strength: 20 },
              { role: 'analyst', strategy: 'Request pre-op CT reconstruction. If fracture has multiple components in distinct zones, separate billing is justified.', strengths: ['Definitive evidence approach'], weaknesses: ['CT may not have been done'], strength: 50 },
              { role: 'breaker', strategy: 'Consider whether cerclage wiring (part of ORIF technique) was needed to stabilize the femur BEFORE THA stem insertion — this is a real surgical need.', strengths: ['Technical surgical knowledge', 'Real clinical scenario'], weaknesses: ['May not match 27236 definition'], strength: 45 },
            ],
          },
        ],
        overallAssessment: 'Likely unbundled. DR-9915 is now flagged in two cases for add-on code patterns. Recommend pattern review and peer comparison.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 68,
        perspectiveStatement: 'The clinical scenario determines everything here. Simple femoral neck fracture → THA alone. Complex multi-fragment fracture → both codes may be justified.',
        keyInsights: [
          'AO/OTA classification of the fracture determines whether ORIF is separately needed',
          'If 31-A3 or 32-A type fracture, subtrochanteric fixation IS separately billable with THA',
          'Pre-op imaging classification is the single most important piece of evidence',
        ],
        assumptions: ['Fracture classification is available', 'Imaging was done pre-op', 'Classification determines billing'],
        violations: [],
        overallAssessment: 'Cannot determine compliance without pre-op imaging and fracture classification. Request CT reconstruction and apply AO/OTA criteria.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 52,
        perspectiveStatement: 'This case highlights a fundamental problem in orthopedic coding — the billing system was designed for elective procedures, not trauma. Trauma cases don\'t fit neatly into single CPT codes.',
        keyInsights: [
          'Trauma coding is inherently more complex than elective coding',
          'Fall from standing (W19.XXXA) in osteoporotic patient = high-energy equivalent fracture',
          'The surgeon may have performed real additional work that the coding system struggles to capture',
        ],
        assumptions: ['Coding system has limitations', 'Trauma adds complexity', 'Documentation may lag clinical reality'],
        violations: [],
        overallAssessment: 'Don\'t pattern-match this with the TKA case (AUD-2024-006). Different clinical scenario, different analysis. Evaluate each case independently.',
      },
    ],
    metadata: { dayOfWeek: 'Thursday', timeOfDay: '11:20', anesthesiaType: 'Spinal', patientObesity: false, understaffing: false, errorsFound: 1, upchargeAmount: 8500, procedureDuration: 145 },
  },
];

export const mockPatterns: PhysicianPattern[] = [
  {
    patternId: 'PAT-001',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    cptCodes: ['99285', '99291', '99292'],
    cases: [mockCases[0], mockCases[4]],
    totalCases: 3,
    rejectionRate: 33,
    totalClaimAmount: 14550,
    averageClaimAmount: 4850,
    dateRange: { start: '2024-01-15', end: '2024-02-17' },
    insights: [
      'High-value claim pattern: Average $4,850 per case (52% above specialty median)',
      'Documentation gaps consistent across cases — missing critical care time logs',
      'Weekend/off-hours services overrepresented (2/3 cases)',
      'Escalating claim amounts over time',
    ],
  },
  {
    patternId: 'PAT-002',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    cptCodes: ['99285', '99291'],
    cases: [mockCases[1]],
    totalCases: 2,
    rejectionRate: 0,
    totalClaimAmount: 7200,
    averageClaimAmount: 3600,
    dateRange: { start: '2024-01-22', end: '2024-02-28' },
    insights: [
      'Claim amounts within normal range for ED + critical care',
      'Better documentation completeness than 3-code pattern',
    ],
  },
  {
    patternId: 'PAT-003',
    physicianId: 'DR-9915',
    physicianName: 'Dr. Richard Tran',
    cptCodes: ['27447', '27130', '20930'],
    cases: [mockCases[5], mockCases[8]],
    totalCases: 2,
    rejectionRate: 0,
    totalClaimAmount: 32950,
    averageClaimAmount: 16475,
    dateRange: { start: '2024-03-04', end: '2024-03-25' },
    insights: [
      'Orthopedic surgeon with consistently high add-on code usage across joint replacement cases',
      'Both cases include bone graft (20930) billed separately — known NCCI edit target',
      'Average claim $16,475 — 3.7x specialty median for arthroplasty',
      'Documentation gaps in both cases (missing implant manifests)',
      'Pattern may indicate systematic unbundling or genuinely complex patient population',
    ],
  },
  {
    patternId: 'PAT-004',
    physicianId: 'DR-5533',
    physicianName: 'Dr. Anika Patel',
    cptCodes: ['22612', '22614', '22842', '63047'],
    cases: [mockCases[6]],
    totalCases: 1,
    rejectionRate: 0,
    totalClaimAmount: 42300,
    averageClaimAmount: 42300,
    dateRange: { start: '2024-03-11', end: '2024-03-11' },
    insights: [
      'Single $42K spine case — highest dollar case in queue',
      'Incomplete operative note is the primary risk factor',
      '5 CPT codes is within NASS guidelines for multi-level fusion but at the high end',
      'Requires complete documentation before pattern can be established',
    ],
  },
];

export const mockEvidenceChecklist: EvidenceChecklistItem[] = [
  { id: 'ec1', description: 'Critical care start/stop time documentation', category: 'documentation', priority: 'high', status: 'missing', relatedCodes: ['99291', '99292'], impactOnRisk: 25 },
  { id: 'ec2', description: 'Medical decision-making complexity documentation', category: 'clinical', priority: 'high', status: 'missing', relatedCodes: ['99285'], impactOnRisk: 20 },
  { id: 'ec3', description: 'Separately billable procedure time exclusions', category: 'coding', priority: 'medium', status: 'missing', relatedCodes: ['99291'], impactOnRisk: 15 },
  { id: 'ec4', description: 'Nursing notes corroborating critical care activities', category: 'documentation', priority: 'medium', status: 'requested', relatedCodes: ['99291', '99292'], impactOnRisk: 10 },
  { id: 'ec5', description: 'EHR audit trail for timestamp verification', category: 'documentation', priority: 'low', status: 'received', relatedCodes: ['99285', '99291'], impactOnRisk: 5 },
  { id: 'ec6', description: 'Laboratory results supporting clinical acuity', category: 'clinical', priority: 'medium', status: 'missing', relatedCodes: ['99285'], impactOnRisk: 8 },
  { id: 'ec7', description: 'Prior authorization for critical care services', category: 'authorization', priority: 'low', status: 'na', relatedCodes: ['99291'], impactOnRisk: 3 },
];

export const mockCodeCombinations: CodeCombinationAnalysis[] = [
  {
    codes: ['99285', '99291'],
    flagReason: 'ED Level 5 + Critical Care same-day billing requires clear documentation of clinical transition from emergency evaluation to critical care management.',
    legitimateExplanations: [
      'Patient presented to ED, stabilized, then condition deteriorated requiring critical care (clear clinical transition)',
      'ED evaluation identified life-threatening condition requiring immediate critical care intervention',
      'Complex multi-system emergency requiring both comprehensive evaluation and ongoing critical management',
    ],
    noncompliantExplanations: [
      'ED evaluation and critical care documentation overlap without clear delineation of separate services',
      'Critical care time includes activities that are part of the ED evaluation (double-counting)',
      'No documented transition point between ED care and critical care management',
    ],
    requiredDocumentation: [
      'Clear documentation of transition from ED to critical care',
      'Separate time documentation for each service',
      'MDM documentation supporting ED Level 5',
      'Critical care time start/stop with excluded procedures',
    ],
  },
  {
    codes: ['99291', '99292'],
    flagReason: 'Critical care initial + add-on requires documentation of total qualifying time exceeding 74 minutes.',
    legitimateExplanations: [
      'Extended resuscitation or stabilization requiring >74 minutes of direct critical care',
      'Complex multi-organ failure management with ongoing interventions',
    ],
    noncompliantExplanations: [
      'Total documented time doesn\'t exclude separately billable procedures',
      'Time documentation is estimated rather than contemporaneous',
    ],
    requiredDocumentation: [
      'Start/stop times for critical care',
      'List of separately billable procedures with times excluded',
      'Total qualifying critical care minutes calculated',
    ],
  },
  {
    codes: ['27447', '20930'],
    flagReason: 'Total knee arthroplasty with separate bone graft billing. NCCI edits pair these codes — modifier 59 required for separate billing.',
    legitimateExplanations: [
      'Structural allograft needed for severe bone deficiency (osteoporosis, revision) with separate harvest site',
      'Bone graft used to fill a defect separate from the arthroplasty bed (e.g., tibial plateau defect)',
      'Morselized allograft ordered as separate implant with its own lot number and invoice',
    ],
    noncompliantExplanations: [
      'Bone graft is part of standard TKA technique — impaction grafting of bone cuts is included',
      'No separate incision or harvest site documented',
      'Graft used within the arthroplasty bed as part of standard implant fixation',
    ],
    requiredDocumentation: [
      'Operative note describing separate graft site and indication',
      'Implant manifest with allograft lot number',
      'Medical necessity for structural vs. standard graft',
      'Modifier 59 or XE/XS documentation',
    ],
  },
  {
    codes: ['22612', '63047'],
    flagReason: 'Posterior lumbar fusion with laminectomy — some payers bundle decompression into fusion approach.',
    legitimateExplanations: [
      'Decompression was the primary procedure; fusion added for instability — sequence documented',
      'Decompression performed at a level adjacent to the fusion level',
      'Separate operative report sections for each procedure with distinct indications',
    ],
    noncompliantExplanations: [
      'Decompression performed at the same level as fusion — may be considered part of the approach',
      'No modifier documentation supporting distinct procedural service',
      'Single operative indication covers both procedures without separate justification',
    ],
    requiredDocumentation: [
      'Level-by-level operative documentation',
      'Fluoroscopic confirmation of levels treated',
      'Separate medical necessity for decompression vs. fusion',
      'NASS-compliant documentation if multi-level',
    ],
  },
  {
    codes: ['44204', '44180'],
    flagReason: 'Laparoscopic colectomy with laparoscopic colostomy — colostomy may be bundled into colectomy (Hartmann\'s procedure).',
    legitimateExplanations: [
      'Colostomy was an unplanned addition due to intraoperative findings (e.g., perforation, ischemia)',
      'Colostomy site preparation and maturation documented as separate surgical work',
      'Payer-specific policy allows separate billing for diversion procedures',
    ],
    noncompliantExplanations: [
      'Hartmann\'s procedure is by definition colectomy + colostomy — single procedure concept',
      'Planned colostomy at time of colectomy is part of the surgical plan, not a separate service',
      'No documentation distinguishing colostomy creation from colectomy endpoint',
    ],
    requiredDocumentation: [
      'Operative note documenting colostomy as distinct decision point',
      'Medical necessity for fecal diversion',
      'Payer-specific bundling rules checked',
      'Intraoperative photos if available',
    ],
  },
  {
    codes: ['27130', '27236'],
    flagReason: 'Total hip arthroplasty with ORIF of femoral fracture — if THA treats the fracture, ORIF is not separately billable.',
    legitimateExplanations: [
      'Complex fracture pattern with subtrochanteric extension requiring separate fixation before THA stem insertion',
      'Cerclage wiring of femoral shaft needed to stabilize fracture before prosthesis placement',
      'Distinct anatomic zones treated: joint (THA) and shaft (ORIF)',
    ],
    noncompliantExplanations: [
      'Simple femoral neck fracture treated with THA — ORIF is an alternative, not an addition',
      'No imaging showing fracture extending beyond the hip joint',
      'Single operative indication without separate justification for ORIF',
    ],
    requiredDocumentation: [
      'Pre-op CT or X-ray showing fracture classification (AO/OTA)',
      'Operative note documenting sequence of fixation then arthroplasty',
      'Intraoperative fluoroscopy confirming separate fixation',
      'Implant manifest for both fixation hardware and prosthesis',
    ],
  },
];
