import type { AuditCase, PhysicianPattern, SOUPYConfig, EvidenceChecklistItem, CodeCombinationAnalysis } from './types';

export const defaultSOUPYConfig: SOUPYConfig = {
  roles: {
    builder: 'GPT-4o',
    redteam: 'Claude 3.5',
    analyst: 'Gemini Pro',
    breaker: 'GPT-4o Mini',
  },
  executionOrder: ['builder', 'redteam', 'analyst', 'breaker'],
};

export const mockCases: AuditCase[] = [
  {
    id: '1',
    caseNumber: 'AUD-2024-001',
    patientId: 'PT-88291',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-01-15',
    dateSubmitted: '2024-01-18',
    status: 'in-review',
    assignedTo: 'John Auditor',
    cptCodes: ['99285', '99291', '99292'],
    icdCodes: ['I21.0', 'R06.02', 'E11.65'],
    claimAmount: 4850,
    consensusScore: 75,
    riskScore: {
      level: 'high',
      score: 78,
      rawScore: 82,
      percentile: 92,
      confidence: 72,
      recommendation: 'Recommend detailed review. Multiple high-value codes with documentation gaps.',
      dataCompleteness: {
        score: 72,
        present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount', 'Physician ID'],
        missing: ['Operative note', 'Critical care time log', 'Lab results'],
      },
      factors: [
        { id: 'f1', title: 'High-value ED + Critical Care combination', description: 'ED level 5 billed same day as critical care', whyItMatters: 'These codes together require clear documentation that critical care was distinct from ED evaluation', evidenceToConfirm: ['Critical care start/stop times', 'ED documentation showing transition to critical care'], weight: 25, isDeterminative: true, triggered: true },
        { id: 'f2', title: 'Multiple add-on units', description: 'Critical care add-on (99292) billed', whyItMatters: 'Additional critical care time must be clearly documented separately', evidenceToConfirm: ['Time logs showing >74 minutes of critical care', 'Activities during additional time'], weight: 20, isDeterminative: true, triggered: true },
        { id: 'f3', title: 'Weekend service date', description: 'Service rendered on a Saturday', whyItMatters: 'Weekend services have higher documentation error rates (not fraud indicator)', evidenceToConfirm: ['Staffing records', 'Attending physician confirmation'], weight: 5, isDeterminative: false, triggered: true },
        { id: 'f4', title: 'Claim amount exceeds specialty median', description: 'Total claim $4,850 vs $3,200 median for similar cases', whyItMatters: 'Higher-than-average claims warrant documentation review', evidenceToConfirm: ['Itemized billing statement', 'Documentation supporting each code'], weight: 15, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [
      {
        role: 'builder',
        model: 'GPT-4o',
        status: 'complete',
        confidence: 72,
        perspectiveStatement: 'The code combination is defensible if documentation supports a genuine clinical escalation from emergency evaluation to critical care management.',
        keyInsights: [
          'STEMI presentation justifies both ED evaluation and critical care',
          'Time-based billing is appropriate if properly documented',
          'ICD codes support medical necessity for critical interventions',
        ],
        assumptions: ['ED evaluation preceded critical care', 'Patient condition genuinely deteriorated', 'Time was properly tracked'],
        violations: [
          {
            id: 'v1', code: '99291', type: 'medical-necessity', severity: 'warning',
            description: 'Critical care time documentation may be insufficient to support billing',
            regulationRef: 'CPT Guidelines §99291-99292; CMS Transmittal 1548',
            defenses: [
              { role: 'builder', strategy: 'STEMI presentation inherently requires critical care management. The clinical scenario supports time-intensive interventions.', strengths: ['Strong clinical indication', 'Life-threatening condition'], weaknesses: ['Missing explicit time documentation'], strength: 68 },
              { role: 'redteam', strategy: 'Without start/stop times, this billing cannot withstand audit scrutiny regardless of clinical merit.', strengths: ['Identifies documentation gap'], weaknesses: ['Ignores clinical context'], strength: 45 },
              { role: 'analyst', strategy: 'CMS requires contemporaneous time documentation. Retrospective attestation may be accepted with corroborating records.', strengths: ['Regulatory framework provided', 'Alternative evidence path'], weaknesses: ['Retrospective documentation weaker'], strength: 55 },
              { role: 'breaker', strategy: 'Consider whether EHR timestamp data can reconstruct critical care time intervals as supporting evidence.', strengths: ['Novel evidence approach', 'Leverages available data'], weaknesses: ['Not standard practice'], strength: 52 },
            ],
          },
          {
            id: 'v2', code: '99285', type: 'upcoding', severity: 'critical',
            description: 'ED visit level 5 requires documentation of immediate, significant threat to life or physiologic function',
            regulationRef: 'AMA CPT Professional Edition; CMS OPPS Guidelines',
            defenses: [
              { role: 'builder', strategy: 'Acute STEMI with respiratory distress clearly meets level 5 criteria for threat to life.', strengths: ['Clear clinical justification', 'ICD codes support acuity'], weaknesses: ['Documentation completeness unknown'], strength: 78 },
              { role: 'redteam', strategy: 'Level 5 is the most scrutinized ED code. Without explicit MDM documentation, downcode to 99284 is likely.', strengths: ['Realistic audit outcome prediction'], weaknesses: ['May undervalue clinical acuity'], strength: 40 },
              { role: 'analyst', strategy: 'MDM elements must be explicitly documented per 2021 E/M guidelines. Check for high-risk diagnoses and data reviewed.', strengths: ['Specific guideline reference', 'Actionable review criteria'], weaknesses: ['Requires documentation review'], strength: 60 },
              { role: 'breaker', strategy: 'The combination of I21.0 + R06.02 statistically correlates with 99285 in >90% of compliant claims. Pattern data supports the code.', strengths: ['Data-driven defense', 'Statistical backing'], weaknesses: ['Pattern ≠ individual compliance'], strength: 55 },
            ],
          },
        ],
        overallAssessment: 'Defensible case with documentation improvements needed. The clinical scenario strongly supports the codes billed, but documentation gaps create audit vulnerability.',
      },
      {
        role: 'redteam',
        model: 'Claude 3.5',
        status: 'complete',
        confidence: 85,
        perspectiveStatement: 'Multiple documentation gaps create significant audit exposure. The billing pattern raises questions that require explicit documentation to resolve.',
        keyInsights: [
          'No critical care time logs found in available records',
          'ED Level 5 + Critical Care same-day billing is a known audit target',
          'Missing documentation for medical decision-making complexity',
        ],
        assumptions: ['Available documentation represents complete record', 'Standard audit criteria will be applied'],
        violations: [
          {
            id: 'v3', code: '99291', type: 'medical-necessity', severity: 'critical',
            description: 'Critical care billing requires contemporaneous time documentation — none found',
            regulationRef: 'CMS IOM Pub 100-04, Ch.12, §30.6.12',
            defenses: [
              { role: 'builder', strategy: 'Clinical acuity of STEMI makes critical care self-evident.', strengths: ['Strong clinical case'], weaknesses: ['Self-evidence insufficient for billing'], strength: 35 },
              { role: 'redteam', strategy: 'This violation is clear-cut. Without time documentation, appeal success rate is <20%.', strengths: ['Honest assessment', 'Prepares for likely outcome'], weaknesses: ['No constructive defense offered'], strength: 20 },
              { role: 'analyst', strategy: 'Seek nursing notes, medication administration records, and EHR audit logs as alternative time evidence.', strengths: ['Identifies alternative evidence sources'], weaknesses: ['Secondary evidence may not satisfy auditors'], strength: 48 },
              { role: 'breaker', strategy: 'Challenge whether the audit criteria is being applied retroactively to a standard that wasn\'t in effect at time of service.', strengths: ['Procedural defense angle'], weaknesses: ['Risky strategy if criteria was current'], strength: 30 },
            ],
          },
        ],
        overallAssessment: 'High audit risk. Recommend requesting complete documentation before making determination. Key gaps in time-based billing support.',
      },
      {
        role: 'analyst',
        model: 'Gemini Pro',
        status: 'complete',
        confidence: 79,
        perspectiveStatement: 'Regulatory framework analysis indicates this code combination requires specific documentation elements that are partially present in the available record.',
        keyInsights: [
          'CMS 2021 E/M guidelines apply — MDM-based scoring required',
          'Critical care time exclusions for separately billable procedures must be documented',
          'Code combination has 34% audit trigger rate nationally',
        ],
        assumptions: ['2021 E/M guidelines in effect', 'Standard MAC audit criteria apply', 'National benchmarks are relevant'],
        violations: [
          {
            id: 'v4', code: '99292', type: 'unbundling', severity: 'warning',
            description: 'Add-on critical care time may overlap with separately billed procedures',
            regulationRef: 'CPT Appendix C; CMS NCCI Edits',
            defenses: [
              { role: 'builder', strategy: 'Multiple interventions during STEMI management justify extended critical care beyond initial 74 minutes.', strengths: ['Clinical justification', 'Complex case'], weaknesses: ['Must prove >74 min of qualifying time'], strength: 62 },
              { role: 'redteam', strategy: 'Burden of proof is on provider. Without explicit time exclusion documentation, this code will be denied.', strengths: ['Clear audit standard'], weaknesses: ['Assumes worst case'], strength: 38 },
              { role: 'analyst', strategy: 'Reconstruct timeline from medication administration records, vital sign timestamps, and procedure logs to calculate qualifying time.', strengths: ['Systematic approach', 'Multiple evidence sources'], weaknesses: ['Time-intensive reconstruction'], strength: 65 },
              { role: 'breaker', strategy: 'Consider whether the clinical complexity itself serves as evidence — STEMI management is inherently >74 minutes.', strengths: ['Appeals to clinical common sense'], weaknesses: ['Not documentation-based'], strength: 42 },
            ],
          },
        ],
        overallAssessment: 'Mixed compliance picture. The regulatory framework supports the clinical scenario, but specific documentation requirements are only partially met.',
      },
      {
        role: 'breaker',
        model: 'GPT-4o Mini',
        status: 'complete',
        confidence: 65,
        perspectiveStatement: 'The traditional audit lens may be missing the forest for the trees. This billing pattern is clinically appropriate — the question is whether documentation practices match clinical reality.',
        keyInsights: [
          'Documentation standards may not reflect actual clinical workflow',
          'EHR design contributes to documentation gaps (system issue, not provider issue)',
          'Similar cases in peer institutions show 78% approval rate with comparable documentation',
        ],
        assumptions: ['Documentation gaps ≠ clinical gaps', 'EHR limitations are systemic', 'Peer comparison is relevant'],
        violations: [],
        overallAssessment: 'Consider systemic factors before individual case determination. Documentation improvement recommendations may be more appropriate than denial.',
      },
    ],
    metadata: {
      dayOfWeek: 'Saturday',
      timeOfDay: '22:30',
      anesthesiaType: 'None',
      patientObesity: false,
      understaffing: true,
      errorsFound: 3,
      upchargeAmount: 1200,
      procedureDuration: 185,
    },
  },
  {
    id: '2',
    caseNumber: 'AUD-2024-002',
    patientId: 'PT-66103',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-01-22',
    dateSubmitted: '2024-01-25',
    status: 'pending',
    cptCodes: ['99285', '99291'],
    icdCodes: ['J96.01', 'R65.20'],
    claimAmount: 3600,
    consensusScore: 88,
    riskScore: {
      level: 'medium',
      score: 55,
      rawScore: 55,
      percentile: 68,
      confidence: 80,
      recommendation: 'Standard review. Code combination is common for critical presentations.',
      dataCompleteness: { score: 80, present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount', 'Physician ID', 'Time documentation'], missing: ['Operative note', 'Lab results'] },
      factors: [
        { id: 'f5', title: 'ED + Critical Care combination', description: 'Common but audited combination', whyItMatters: 'Requires clear clinical escalation documentation', evidenceToConfirm: ['Time logs', 'Clinical transition notes'], weight: 20, isDeterminative: true, triggered: true },
        { id: 'f6', title: 'Claim within normal range', description: 'Amount is within 1 SD of specialty median', whyItMatters: 'Lower statistical outlier risk', evidenceToConfirm: [], weight: 5, isDeterminative: false, triggered: false },
      ],
    },
    analyses: [],
    metadata: { dayOfWeek: 'Monday', timeOfDay: '14:15', anesthesiaType: 'None', patientObesity: true, understaffing: false, errorsFound: 1, upchargeAmount: 400, procedureDuration: 120 },
  },
  {
    id: '3',
    caseNumber: 'AUD-2024-003',
    patientId: 'PT-44290',
    physicianId: 'DR-7722',
    physicianName: 'Dr. James Park',
    dateOfService: '2024-02-03',
    dateSubmitted: '2024-02-06',
    status: 'approved',
    assignedTo: 'Jane Reviewer',
    cptCodes: ['43235', '43239'],
    icdCodes: ['K21.0', 'K29.70'],
    claimAmount: 2100,
    consensusScore: 95,
    riskScore: {
      level: 'low',
      score: 25,
      rawScore: 25,
      percentile: 22,
      confidence: 90,
      recommendation: 'Low risk. Standard GI procedure with appropriate coding.',
      dataCompleteness: { score: 90, present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pathology report', 'Physician ID', 'Service metadata'], missing: ['Prior authorization'] },
      factors: [
        { id: 'f7', title: 'Standard procedure combination', description: 'Diagnostic + biopsy is common', whyItMatters: 'Typical billing pattern for GI procedures', evidenceToConfirm: [], weight: 5, isDeterminative: false, triggered: false },
      ],
    },
    analyses: [],
    decision: { outcome: 'approved', reasoning: 'All documentation supports codes billed. Pathology report confirms biopsy necessity.', auditor: 'Jane Reviewer', timestamp: '2024-02-08T10:30:00Z', overrides: [] },
    metadata: { dayOfWeek: 'Wednesday', timeOfDay: '09:00', anesthesiaType: 'Conscious Sedation', patientObesity: false, understaffing: false, errorsFound: 0, upchargeAmount: 0, procedureDuration: 45 },
  },
  {
    id: '4',
    caseNumber: 'AUD-2024-004',
    patientId: 'PT-55120',
    physicianId: 'DR-7722',
    physicianName: 'Dr. James Park',
    dateOfService: '2024-02-10',
    dateSubmitted: '2024-02-13',
    status: 'rejected',
    assignedTo: 'John Auditor',
    cptCodes: ['29880', '29881'],
    icdCodes: ['M23.21', 'M17.11'],
    claimAmount: 5200,
    consensusScore: 40,
    riskScore: {
      level: 'critical',
      score: 91,
      rawScore: 98,
      percentile: 98,
      confidence: 85,
      recommendation: 'High risk of overbilling. Both meniscectomy codes billed for same knee requires strong justification.',
      dataCompleteness: { score: 85, present: ['CPT codes', 'ICD-10 codes', 'Operative note', 'Pre-op imaging', 'Physician ID', 'Service metadata'], missing: ['Distinct compartment documentation'] },
      factors: [
        { id: 'f8', title: 'Duplicate meniscectomy codes', description: '29880 and 29881 billed together', whyItMatters: '29880 includes both compartments — billing 29881 additionally suggests unbundling', evidenceToConfirm: ['Operative note showing distinct work in separate compartments', 'Medical necessity for both procedures'], weight: 35, isDeterminative: true, triggered: true },
        { id: 'f9', title: 'High claim amount', description: '$5,200 is 2.1x specialty median', whyItMatters: 'Significant financial outlier', evidenceToConfirm: ['Itemized billing', 'Justification for each code'], weight: 20, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [],
    decision: { outcome: 'rejected', reasoning: 'Operative note does not support billing both 29880 and 29881. 29880 includes medial AND lateral meniscectomy. Recommend rebilling with 29880 only.', auditor: 'John Auditor', timestamp: '2024-02-15T14:00:00Z', overrides: [] },
    metadata: { dayOfWeek: 'Friday', timeOfDay: '07:30', anesthesiaType: 'General', patientObesity: true, understaffing: false, errorsFound: 2, upchargeAmount: 2600, procedureDuration: 90 },
  },
  {
    id: '5',
    caseNumber: 'AUD-2024-005',
    patientId: 'PT-77443',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    dateOfService: '2024-02-17',
    dateSubmitted: '2024-02-20',
    status: 'pending',
    cptCodes: ['99285', '99291', '99292'],
    icdCodes: ['I46.9', 'J96.00'],
    claimAmount: 5100,
    consensusScore: 70,
    riskScore: {
      level: 'high',
      score: 80,
      rawScore: 85,
      percentile: 94,
      confidence: 68,
      recommendation: 'Pattern detected: Third case from same physician with identical code combination. Recommend pattern analysis.',
      dataCompleteness: { score: 68, present: ['CPT codes', 'ICD-10 codes', 'Service metadata', 'Claim amount'], missing: ['Critical care time log', 'Operative note', 'Lab results', 'Nursing notes'] },
      factors: [
        { id: 'f10', title: 'Repeat code pattern', description: 'Same physician, same CPT combination (3rd occurrence)', whyItMatters: 'Recurring patterns may indicate systemic billing practices', evidenceToConfirm: ['Pattern analysis review', 'Peer comparison'], weight: 30, isDeterminative: true, triggered: true },
        { id: 'f11', title: 'Off-hours service', description: 'Service at 03:15 AM', whyItMatters: 'Off-hours services have higher documentation error likelihood', evidenceToConfirm: ['Staffing records', 'Attending attestation'], weight: 5, isDeterminative: false, triggered: true },
      ],
    },
    analyses: [],
    metadata: { dayOfWeek: 'Sunday', timeOfDay: '03:15', anesthesiaType: 'None', patientObesity: false, understaffing: true, errorsFound: 4, upchargeAmount: 1800, procedureDuration: 210 },
  },
];

export const mockPatterns: PhysicianPattern[] = [
  {
    patternId: 'PAT-001',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    cptCodes: ['99285', '99291', '99292'],
    cases: [mockCases[0], mockCases[4]],
    totalCases: 3,
    rejectionRate: 33,
    totalClaimAmount: 14550,
    averageClaimAmount: 4850,
    dateRange: { start: '2024-01-15', end: '2024-02-17' },
    insights: [
      'High-value claim pattern: Average $4,850 per case (52% above specialty median)',
      'Documentation gaps consistent across cases — missing critical care time logs',
      'Weekend/off-hours services overrepresented (2/3 cases)',
      'Escalating claim amounts over time',
    ],
  },
  {
    patternId: 'PAT-002',
    physicianId: 'DR-4401',
    physicianName: 'Dr. Sarah Mitchell',
    cptCodes: ['99285', '99291'],
    cases: [mockCases[1]],
    totalCases: 2,
    rejectionRate: 0,
    totalClaimAmount: 7200,
    averageClaimAmount: 3600,
    dateRange: { start: '2024-01-22', end: '2024-02-28' },
    insights: [
      'Claim amounts within normal range for ED + critical care',
      'Better documentation completeness than 3-code pattern',
    ],
  },
];

export const mockEvidenceChecklist: EvidenceChecklistItem[] = [
  { id: 'ec1', description: 'Critical care start/stop time documentation', category: 'documentation', priority: 'high', status: 'missing', relatedCodes: ['99291', '99292'], impactOnRisk: 25 },
  { id: 'ec2', description: 'Medical decision-making complexity documentation', category: 'clinical', priority: 'high', status: 'missing', relatedCodes: ['99285'], impactOnRisk: 20 },
  { id: 'ec3', description: 'Separately billable procedure time exclusions', category: 'coding', priority: 'medium', status: 'missing', relatedCodes: ['99291'], impactOnRisk: 15 },
  { id: 'ec4', description: 'Nursing notes corroborating critical care activities', category: 'documentation', priority: 'medium', status: 'requested', relatedCodes: ['99291', '99292'], impactOnRisk: 10 },
  { id: 'ec5', description: 'EHR audit trail for timestamp verification', category: 'documentation', priority: 'low', status: 'received', relatedCodes: ['99285', '99291'], impactOnRisk: 5 },
  { id: 'ec6', description: 'Laboratory results supporting clinical acuity', category: 'clinical', priority: 'medium', status: 'missing', relatedCodes: ['99285'], impactOnRisk: 8 },
  { id: 'ec7', description: 'Prior authorization for critical care services', category: 'authorization', priority: 'low', status: 'na', relatedCodes: ['99291'], impactOnRisk: 3 },
];

export const mockCodeCombinations: CodeCombinationAnalysis[] = [
  {
    codes: ['99285', '99291'],
    flagReason: 'ED Level 5 + Critical Care same-day billing requires clear documentation of clinical transition from emergency evaluation to critical care management.',
    legitimateExplanations: [
      'Patient presented to ED, stabilized, then condition deteriorated requiring critical care (clear clinical transition)',
      'ED evaluation identified life-threatening condition requiring immediate critical care intervention',
      'Complex multi-system emergency requiring both comprehensive evaluation and ongoing critical management',
    ],
    noncompliantExplanations: [
      'ED evaluation and critical care documentation overlap without clear delineation of separate services',
      'Critical care time includes activities that are part of the ED evaluation (double-counting)',
      'No documented transition point between ED care and critical care management',
    ],
    requiredDocumentation: [
      'Clear documentation of transition from ED to critical care',
      'Separate time documentation for each service',
      'MDM documentation supporting ED Level 5',
      'Critical care time start/stop with excluded procedures',
    ],
  },
  {
    codes: ['99291', '99292'],
    flagReason: 'Critical care initial + add-on requires documentation of total qualifying time exceeding 74 minutes.',
    legitimateExplanations: [
      'Extended resuscitation or stabilization requiring >74 minutes of direct critical care',
      'Complex multi-organ failure management with ongoing interventions',
    ],
    noncompliantExplanations: [
      'Total documented time doesn\'t exclude separately billable procedures',
      'Time documentation is estimated rather than contemporaneous',
    ],
    requiredDocumentation: [
      'Start/stop times for critical care',
      'List of separately billable procedures with times excluded',
      'Total qualifying critical care minutes calculated',
    ],
  },
];
