import type { ORReadinessEvent, TriageAccuracyEvent, PostOpFlowEvent } from './operationalTypes';

export const mockORReadinessEvents: ORReadinessEvent[] = [
  {
    id: 'or-1', case_id: 'case-1', room_id: 'OR-3', event_type: 'dropped_implant',
    delay_minutes: 22, replacement_source: 'Vendor rep on-site', patient_wait_status: 'under_anesthesia',
    classification: 'isolated', vendor_rep: 'Stryker – J. Davis', service_line: 'Orthopedics',
    shift: 'AM', day_of_week: 'Monday', estimated_cost: 1760, safety_flag: false,
    notes: 'Knee implant dropped during handoff. Backup available from rep.', created_at: '2026-04-10T08:30:00Z',
  },
  {
    id: 'or-2', case_id: 'case-2', room_id: 'OR-1', event_type: 'sterilization_lapse',
    delay_minutes: 45, replacement_source: 'Central sterile reprocessing', patient_wait_status: 'under_anesthesia',
    classification: 'workflow_issue', service_line: 'General Surgery',
    shift: 'AM', day_of_week: 'Tuesday', estimated_cost: 5400, safety_flag: true,
    notes: 'Tray arrived with broken seal. Full reprocessing required.', created_at: '2026-04-09T07:15:00Z',
  },
  {
    id: 'or-3', case_id: 'case-3', room_id: 'OR-5', event_type: 'wrong_size',
    delay_minutes: 35, replacement_source: 'Hospital inventory', patient_wait_status: 'under_anesthesia',
    classification: 'repeat_pattern', vendor_rep: 'Zimmer – M. Chen', service_line: 'Orthopedics',
    shift: 'PM', day_of_week: 'Monday', estimated_cost: 2800, safety_flag: false,
    notes: 'Third time wrong size hip stem delivered for this surgeon.', created_at: '2026-04-08T14:00:00Z',
  },
  {
    id: 'or-4', room_id: 'OR-2', event_type: 'missing_instrument',
    delay_minutes: 12, replacement_source: 'Borrowed from adjacent OR', patient_wait_status: 'stable',
    classification: 'isolated', service_line: 'Neurosurgery',
    shift: 'AM', day_of_week: 'Wednesday', estimated_cost: 960, safety_flag: false,
    notes: 'Kerrison rongeur missing from tray.', created_at: '2026-04-07T09:45:00Z',
  },
  {
    id: 'or-5', room_id: 'OR-3', event_type: 'dropped_implant',
    delay_minutes: 18, replacement_source: 'Vendor rep on-site', patient_wait_status: 'under_anesthesia',
    classification: 'workflow_issue', vendor_rep: 'Stryker – J. Davis', service_line: 'Orthopedics',
    shift: 'PM', day_of_week: 'Monday', estimated_cost: 1440, safety_flag: false,
    notes: 'Second drop incident in OR-3 this month.', created_at: '2026-04-06T13:20:00Z',
  },
  {
    id: 'or-6', room_id: 'OR-1', event_type: 'contaminated',
    delay_minutes: 50, replacement_source: 'Emergency vendor call', patient_wait_status: 'under_anesthesia',
    classification: 'repeat_pattern', vendor_rep: 'Zimmer – M. Chen', service_line: 'Orthopedics',
    shift: 'AM', day_of_week: 'Thursday', estimated_cost: 6000, safety_flag: true,
    notes: 'Contaminated packaging on hip liner. Second contamination event this quarter.', created_at: '2026-04-04T08:00:00Z',
  },
  {
    id: 'or-7', room_id: 'OR-4', event_type: 'tray_not_ready',
    delay_minutes: 30, replacement_source: 'Central sterile rush processing', patient_wait_status: 'awake_waiting',
    classification: 'workflow_issue', service_line: 'General Surgery',
    shift: 'AM', day_of_week: 'Monday', estimated_cost: 2400, safety_flag: false,
    notes: 'Monday AM tray turnaround consistently delayed due to weekend backlog.', created_at: '2026-04-03T07:30:00Z',
  },
  {
    id: 'or-8', room_id: 'OR-1', event_type: 'sterilization_lapse',
    delay_minutes: 40, replacement_source: 'Central sterile reprocessing', patient_wait_status: 'under_anesthesia',
    classification: 'repeat_pattern', service_line: 'General Surgery',
    shift: 'AM', day_of_week: 'Friday', estimated_cost: 4800, safety_flag: true,
    notes: 'Third sterilization lapse in OR-1 this quarter. Process review escalated.', created_at: '2026-03-28T07:45:00Z',
  },
];

export const mockTriageEvents: TriageAccuracyEvent[] = [
  {
    id: 'tri-1', case_id: 'case-1', booker_name: 'K. Martinez', surgeon_name: 'Dr. Patel',
    service_line: 'Orthopedics', expected_procedure: 'Total Knee Arthroplasty',
    actual_procedure: 'Total Knee Arthroplasty w/ Revision Components', expected_duration: 90,
    actual_duration: 145, expected_implant: 'Primary TKA System', actual_implant: 'Revision Augment + Stems',
    expected_staff_count: 3, actual_staff_count: 5,
    extra_equipment: ['Revision tray', 'Bone cement mixer'], unplanned_support: ['Second scrub tech'],
    foreseeability_score: 72, foreseeability_class: 'predictable', complexity_delta: 3.2,
    follow_up_status: 'completed', follow_up_notes: 'Scheduler retrained on revision booking protocol.',
    month: '2026-04',
    notes: 'Pre-op X-ray showed bone loss. Should have been booked as potential revision.', created_at: '2026-04-10T08:00:00Z',
  },
  {
    id: 'tri-2', booker_name: 'L. Thompson', surgeon_name: 'Dr. Kim',
    service_line: 'General Surgery', expected_procedure: 'Laparoscopic Cholecystectomy',
    actual_procedure: 'Open Cholecystectomy + CBD Exploration', expected_duration: 60,
    actual_duration: 140, expected_implant: 'None', actual_implant: 'T-tube drain',
    expected_staff_count: 3, actual_staff_count: 4,
    extra_equipment: ['Open tray', 'Cholangiogram supplies'], unplanned_support: ['Anesthesia attending'],
    foreseeability_score: 35, foreseeability_class: 'unavoidable', complexity_delta: 4.5,
    follow_up_status: 'none', month: '2026-04',
    notes: 'Extensive adhesions from prior surgery. Conversion clinically appropriate.', created_at: '2026-04-09T10:00:00Z',
  },
  {
    id: 'tri-3', booker_name: 'K. Martinez', surgeon_name: 'Dr. Patel',
    service_line: 'Orthopedics', expected_procedure: 'Hip Arthroplasty',
    actual_procedure: 'Hip Arthroplasty + Fracture Fixation', expected_duration: 120,
    actual_duration: 195, expected_implant: 'Cementless Hip System',
    actual_implant: 'Cemented Hip System + Cables', expected_staff_count: 4, actual_staff_count: 6,
    extra_equipment: ['Cable cerclage system'],
    unplanned_support: ['Trauma fellow'], foreseeability_score: 58,
    foreseeability_class: 'partially_foreseeable', complexity_delta: 2.8,
    follow_up_status: 'pending', follow_up_notes: 'Awaiting scheduler meeting.',
    month: '2026-04',
    notes: 'Intra-op fracture during reaming. History of osteoporosis was documented.', created_at: '2026-04-08T07:30:00Z',
  },
  {
    id: 'tri-4', booker_name: 'K. Martinez', surgeon_name: 'Dr. Patel',
    service_line: 'Orthopedics', expected_procedure: 'Rotator Cuff Repair',
    actual_procedure: 'Rotator Cuff Repair + Biceps Tenodesis', expected_duration: 75,
    actual_duration: 130, expected_implant: 'Suture Anchors x3',
    actual_implant: 'Suture Anchors x5 + Biceps Button', expected_staff_count: 3, actual_staff_count: 4,
    extra_equipment: ['Biceps tenodesis set'], unplanned_support: [],
    foreseeability_score: 65, foreseeability_class: 'predictable', complexity_delta: 2.1,
    follow_up_status: 'none', month: '2026-03',
    notes: 'MRI clearly showed biceps involvement. Should have been booked as combined.', created_at: '2026-03-22T09:00:00Z',
  },
  {
    id: 'tri-5', booker_name: 'L. Thompson', surgeon_name: 'Dr. Kim',
    service_line: 'General Surgery', expected_procedure: 'Inguinal Hernia Repair',
    actual_procedure: 'Bilateral Inguinal Hernia Repair', expected_duration: 45,
    actual_duration: 85, expected_implant: 'Mesh x1',
    actual_implant: 'Mesh x2', expected_staff_count: 2, actual_staff_count: 3,
    extra_equipment: ['Additional mesh'], unplanned_support: [],
    foreseeability_score: 80, foreseeability_class: 'predictable', complexity_delta: 1.8,
    follow_up_status: 'escalated', follow_up_notes: 'CT clearly showed bilateral defect. Booking error.',
    month: '2026-03',
    notes: 'CT report documented bilateral hernias. Booking only reflected unilateral.', created_at: '2026-03-15T11:00:00Z',
  },
  {
    id: 'tri-6', booker_name: 'R. Chen', surgeon_name: 'Dr. Lee',
    service_line: 'Neurosurgery', expected_procedure: 'Lumbar Microdiscectomy',
    actual_procedure: 'Lumbar Microdiscectomy', expected_duration: 90,
    actual_duration: 95, expected_implant: 'None',
    actual_implant: 'None', expected_staff_count: 3, actual_staff_count: 3,
    extra_equipment: [], unplanned_support: [],
    foreseeability_score: 10, foreseeability_class: 'unavoidable', complexity_delta: 0.2,
    follow_up_status: 'none', month: '2026-04',
    notes: 'Booking matched actual. Well-triaged case.', created_at: '2026-04-05T08:30:00Z',
  },
];

export const mockPostOpFlowEvents: PostOpFlowEvent[] = [
  {
    id: 'po-1', case_id: 'case-1', patient_wait_minutes: 42, staff_idle_minutes: 25,
    delay_reason: 'No PACU bed available', delay_category: 'bed_misallocation',
    facility: 'Main Campus', surgeon_name: 'Dr. Patel',
    service_line: 'Orthopedics', day_of_week: 'Monday', shift: 'AM', bed_available: false,
    extra_anesthesia_minutes: 20, extra_monitoring_minutes: 42,
    notes: 'Patient kept under light anesthesia. PACU at capacity from overnight backlog.', created_at: '2026-04-10T11:30:00Z',
  },
  {
    id: 'po-2', patient_wait_minutes: 28, staff_idle_minutes: 15,
    delay_reason: 'Miscommunication with transport', delay_category: 'miscommunication',
    facility: 'Main Campus', surgeon_name: 'Dr. Kim',
    service_line: 'General Surgery', day_of_week: 'Tuesday', shift: 'AM', bed_available: true,
    extra_anesthesia_minutes: 0, extra_monitoring_minutes: 28,
    notes: 'Bed was available but transport never called. OR nurse had to walk patient.', created_at: '2026-04-09T12:15:00Z',
  },
  {
    id: 'po-3', patient_wait_minutes: 55, staff_idle_minutes: 40,
    delay_reason: 'Scheduling overlap — two cases finishing simultaneously', delay_category: 'scheduling_overlap',
    facility: 'Ambulatory Center',
    surgeon_name: 'Dr. Patel', service_line: 'Orthopedics', day_of_week: 'Monday', shift: 'PM',
    bed_available: false, extra_anesthesia_minutes: 30, extra_monitoring_minutes: 55,
    intervention_applied: 'Staggered case start times', intervention_effective: false,
    notes: 'Chronic Monday PM bottleneck. Both ORs release patients to single recovery bay.', created_at: '2026-04-07T15:00:00Z',
  },
  {
    id: 'po-4', patient_wait_minutes: 15, staff_idle_minutes: 5,
    delay_reason: 'Brief handoff delay', delay_category: 'other',
    facility: 'Main Campus', surgeon_name: 'Dr. Lee',
    service_line: 'Neurosurgery', day_of_week: 'Wednesday', shift: 'AM', bed_available: true,
    extra_anesthesia_minutes: 0, extra_monitoring_minutes: 5,
    notes: 'Minimal delay. Within acceptable range.', created_at: '2026-04-06T10:45:00Z',
  },
  {
    id: 'po-5', patient_wait_minutes: 38, staff_idle_minutes: 20,
    delay_reason: 'Overcrowded PACU', delay_category: 'pacu_understaffing',
    facility: 'Main Campus', surgeon_name: 'Dr. Kim',
    service_line: 'General Surgery', day_of_week: 'Monday', shift: 'AM', bed_available: false,
    extra_anesthesia_minutes: 15, extra_monitoring_minutes: 38,
    intervention_applied: 'Called additional PACU nurse', intervention_effective: true,
    notes: 'Monday mornings consistently show PACU saturation.', created_at: '2026-04-05T11:00:00Z',
  },
  {
    id: 'po-6', patient_wait_minutes: 48, staff_idle_minutes: 30,
    delay_reason: 'Emergent trauma case took only available bed', delay_category: 'emergent_bump',
    facility: 'Main Campus', surgeon_name: 'Dr. Patel',
    service_line: 'Orthopedics', day_of_week: 'Thursday', shift: 'PM', bed_available: false,
    extra_anesthesia_minutes: 25, extra_monitoring_minutes: 48,
    notes: 'Trauma activation redirected PACU resources. Elective patients queued.', created_at: '2026-04-03T14:30:00Z',
  },
  {
    id: 'po-7', patient_wait_minutes: 22, staff_idle_minutes: 10,
    delay_reason: 'Transport delayed by elevator maintenance', delay_category: 'transport_delay',
    facility: 'Ambulatory Center', surgeon_name: 'Dr. Lee',
    service_line: 'Neurosurgery', day_of_week: 'Friday', shift: 'AM', bed_available: true,
    extra_anesthesia_minutes: 0, extra_monitoring_minutes: 12,
    notes: 'Infrastructure issue. Facilities notified.', created_at: '2026-04-02T09:00:00Z',
  },
];
