import type { PsychCaseInput } from './psychTypes';

export const DEMO_PSYCH_CASES: PsychCaseInput[] = [
  {
    id: 'demo-1',
    patientLabel: 'Patient A',
    sessionType: 'individual_therapy',
    cptCode: '90837',
    diagnosisCodes: ['F33.1'],
    sessionDurationMinutes: 38,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 185,
    dateOfService: '2026-04-14',
    payerName: 'UnitedHealthcare',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: false, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-2',
    patientLabel: 'Patient B',
    sessionType: 'telehealth',
    cptCode: '90834',
    diagnosisCodes: ['F41.1'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '02',
    isTelehealth: true,
    hasTelehealthConsent: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    payerName: 'Aetna',
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: false,
    hasPatientLocationDocumented: false,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    hasScreeningTools: true,
    screeningToolsUsed: ['GAD-7'],
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-3',
    patientLabel: 'Patient C',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F32.1'],
    sessionDurationMinutes: 48,
    hasCurrentTreatmentPlan: false,
    treatmentPlanExpiry: '2026-02-01',
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-13',
    payerName: 'Anthem BCBS',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    consentReattestationDue: '2026-03-15',
    hasScreeningTools: true,
    screeningToolsUsed: ['PHQ-9'],
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: false, hasTreatmentResponse: true, hasMoodAffectDetail: false, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-4',
    patientLabel: 'Patient D',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F43.10'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: false,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-12',
    payerName: 'Cigna',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-5',
    patientLabel: 'Patient E',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F40.10'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: false,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-11',
    payerName: 'UnitedHealthcare',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: false,
    hasCrisisSafetyPlan: false,
    hasPatientLocationDocumented: false,
    hasEmergencyContactOnFile: false,
    patientState: 'FL',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: false, hasSymptomSeverity: false, hasTreatmentResponse: false, hasMoodAffectDetail: false, hasSessionJustification: true, hasContinuedCareRationale: false, appearsCloned: true },
  },
  {
    id: 'demo-6',
    patientLabel: 'Patient F',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F33.0'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    requiresSupervision: true,
    hasSupervisingProvider: false,
    payerName: 'Medicaid',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-7',
    patientLabel: 'Patient G',
    sessionType: 'medication_management',
    cptCode: '99214',
    diagnosisCodes: ['F31.31'],
    sessionDurationMinutes: 30,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 175,
    dateOfService: '2026-04-14',
    payerName: 'Anthem BCBS',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    hasCollaborativeCareAgreement: false,
    hasPharmacogenomicTesting: false,
    emInput: {
      selectedEMCode: '99214',
      problemsAddressed: 2,
      isNewProblem: false,
      dataReviewed: ['labs', 'medication_history'],
      riskLevel: 'moderate',
      hasIndependentInterpretation: false,
      hasAssessmentPlan: true,
    },
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-8',
    patientLabel: 'Patient H',
    sessionType: 'medication_management',
    cptCode: '99213',
    diagnosisCodes: ['F32.1', 'F41.1'],
    sessionDurationMinutes: 35,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 130,
    dateOfService: '2026-04-13',
    payerName: 'UnitedHealthcare',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    hasCollaborativeCareAgreement: false,
    hasPharmacogenomicTesting: false,
    hasScreeningTools: true,
    screeningToolsUsed: ['PHQ-9', 'GAD-7'],
    emInput: {
      selectedEMCode: '99213',
      problemsAddressed: 3,
      isNewProblem: false,
      dataReviewed: ['labs', 'medication_history', 'records'],
      riskLevel: 'moderate',
      hasIndependentInterpretation: true,
      hasAssessmentPlan: true,
    },
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-9',
    patientLabel: 'Patient I',
    sessionType: 'intake_evaluation',
    cptCode: '90791',
    diagnosisCodes: ['F33.2'],
    sessionDurationMinutes: 60,
    hasCurrentTreatmentPlan: false,
    hasAuthorizationOnFile: true,
    hasProgressNotes: false,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 250,
    dateOfService: '2026-04-14',
    payerName: 'Cigna',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    totalIntakeMinutes: 75,
  },
  {
    id: 'demo-10',
    patientLabel: 'Patient J',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F41.9'],
    sessionDurationMinutes: 55,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    payerName: 'Aetna',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    sessionFrequencyPerWeek: 1,
    documentedAcuityLevel: 'moderate',
    hasScreeningTools: true,
    screeningToolsUsed: ['GAD-7', 'PHQ-9'],
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  // ── Telehealth edge cases ──
  {
    id: 'demo-11',
    patientLabel: 'Patient K',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F43.21'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    isAudioOnly: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-15',
    payerName: 'UnitedHealthcare',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: false,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'FL',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-12',
    patientLabel: 'Patient L',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F41.1'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '10',
    isTelehealth: true,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-15',
    payerName: 'Aetna',
    hasTelehealthConsent: true,
    telehealthPlatformDocumented: true,
    hasCrisisSafetyPlan: true,
    hasPatientLocationDocumented: true,
    hasEmergencyContactOnFile: true,
    patientState: 'GA',
    providerState: 'FL',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
];
