import type { PsychCaseInput } from './psychTypes';

export const DEMO_PSYCH_CASES: PsychCaseInput[] = [
  {
    id: 'demo-1',
    patientLabel: 'Patient A',
    sessionType: 'individual_therapy',
    cptCode: '90837',
    diagnosisCodes: ['F33.1'],
    sessionDurationMinutes: 38,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 185,
    dateOfService: '2026-04-14',
    payerName: 'UnitedHealthcare',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: false, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-2',
    patientLabel: 'Patient B',
    sessionType: 'telehealth',
    cptCode: '90834',
    diagnosisCodes: ['F41.1'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: true,
    hasTelehealthConsent: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    payerName: 'Aetna',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-3',
    patientLabel: 'Patient C',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F32.1'],
    sessionDurationMinutes: 48,
    hasCurrentTreatmentPlan: false,
    treatmentPlanExpiry: '2026-02-01',
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-13',
    payerName: 'Anthem BCBS',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: false, hasTreatmentResponse: true, hasMoodAffectDetail: false, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-4',
    patientLabel: 'Patient D',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F43.10'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: false,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-12',
    payerName: 'Cigna',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-5',
    patientLabel: 'Patient E',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F40.10'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: false,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-11',
    payerName: 'UnitedHealthcare',
    noteQuality: { hasFunctionalImpairment: false, hasSymptomSeverity: false, hasTreatmentResponse: false, hasMoodAffectDetail: false, hasSessionJustification: true, hasContinuedCareRationale: false, appearsCloned: true },
  },
  {
    id: 'demo-6',
    patientLabel: 'Patient F',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F33.0'],
    sessionDurationMinutes: 45,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    requiresSupervision: true,
    hasSupervisingProvider: false,
    payerName: 'Medicaid',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-7',
    patientLabel: 'Patient G',
    sessionType: 'medication_management',
    cptCode: '99214',
    diagnosisCodes: ['F31.31'],
    sessionDurationMinutes: 30,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 175,
    dateOfService: '2026-04-14',
    payerName: 'Anthem BCBS',
    emInput: {
      selectedEMCode: '99214',
      problemsAddressed: 2,
      isNewProblem: false,
      dataReviewed: ['labs', 'medication_history'],
      riskLevel: 'moderate',
      hasIndependentInterpretation: false,
      hasAssessmentPlan: true,
    },
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-8',
    patientLabel: 'Patient H',
    sessionType: 'medication_management',
    cptCode: '99213',
    diagnosisCodes: ['F32.1', 'F41.1'],
    sessionDurationMinutes: 35,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 130,
    dateOfService: '2026-04-13',
    payerName: 'UnitedHealthcare',
    emInput: {
      selectedEMCode: '99213',
      problemsAddressed: 3,
      isNewProblem: false,
      dataReviewed: ['labs', 'medication_history', 'records'],
      riskLevel: 'moderate',
      hasIndependentInterpretation: true,
      hasAssessmentPlan: true,
    },
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
  {
    id: 'demo-9',
    patientLabel: 'Patient I',
    sessionType: 'intake_evaluation',
    cptCode: '90791',
    diagnosisCodes: ['F33.2'],
    sessionDurationMinutes: 60,
    hasCurrentTreatmentPlan: false,
    hasAuthorizationOnFile: true,
    hasProgressNotes: false,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 250,
    dateOfService: '2026-04-14',
    payerName: 'Cigna',
  },
  {
    id: 'demo-10',
    patientLabel: 'Patient J',
    sessionType: 'individual_therapy',
    cptCode: '90834',
    diagnosisCodes: ['F41.9'],
    sessionDurationMinutes: 55,
    hasCurrentTreatmentPlan: true,
    hasAuthorizationOnFile: true,
    hasProgressNotes: true,
    hasMedicalNecessityStatement: true,
    placeOfService: '11',
    isTelehealth: false,
    hasStartStopTime: true,
    claimAmount: 150,
    dateOfService: '2026-04-14',
    payerName: 'Aetna',
    sessionFrequencyPerWeek: 1,
    documentedAcuityLevel: 'moderate',
    noteQuality: { hasFunctionalImpairment: true, hasSymptomSeverity: true, hasTreatmentResponse: true, hasMoodAffectDetail: true, hasSessionJustification: true, hasContinuedCareRationale: true, appearsCloned: false },
  },
];
